### ISSUE TITLE
[Feature request] Support data URIs

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#102]
## Steps to reproduce
* Tap on the URL bar.
 * Write `data:text/html,<input type=file>`
 
 ### Expected behavior
See a file input (probably).
 
### Actual behavior
Searches for my data URL.

**Comment by plateaukao** [comment]
Hi, @Kita2345 
May I know in what scenario a user will try to use data URI as input? In most cases, users won't know what data URI is, and they won't copy data URIs either. If this is a very rare usage, I may not spend time on supporting this.

**Comment by plateaukao** [comment]
no further information. close it for now.
