### ISSUE TITLE
Is there any way to open Home page in new tab every time?

### ISSUE THREAD

**Issue by Licarde** [plateaukao/einkbro#109]
I'm using einkbro with boox nova 2 and this is my favorite browser. When I open new tab in my smartphone, I can catch headlines in Yahoo homepage. But in boox, I can't. So any one tell me how to set new tab as homepage, or if this browser doesn't have such a function, add it please.

**Comment by plateaukao** [comment]
I will check if there's any way to make new tab feature more flexible.

**Comment by plateaukao** [comment]
@Licarde 
This feature is added, you could try nightly build on Readme description, or, wait for release v9.10.0
