### ISSUE TITLE
Downloading files that requires Referer header 

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#125]
Go to https://dl.twrp.me/guacamole/twrp-installer-3.5.0_9-0-guacamole.zip and try to download the .zip file.

After download the file is 6,99KB instead 17,59MB, because the browser downloads the HTML instead of the .zip file.

**Comment by plateaukao** [comment]
no redirect link is supported by Android's Download Manager; so, please try other browser when it happens.
