### ISSUE TITLE
Request:  Override non-resizeable web pages

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/einkbro#138]
Issue:  some webpages disable user zoom / resize capability.

Request:  override the site preference and elevate user preference.

Example:

<https://blog.britishmuseum.org/ancient-healthcare-fit-for-a-king/>

Page displays text in a narrow left-aligned column.  My preference is to zoom the page to column width, then reduce font size such that I get roughly 60 characters/line.

Presently the site and EinkBro don't support this.

I believe there may be multiple methods by which sites accomplish this, with one being a `<meta>` tag.  See:

<https://www.w3docs.com/snippets/css/how-to-disable-zoom-on-a-mobile-web-page-using-html-and-css.html>

That seems to be the case in at least this instance, as the URL I've provided has this tag:

```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
```

EinkBro should simply ignore the portions of that which disable readers' own zoom preferences.  That's the "maximum-scale" value AFAIU (which is little).  "minimum-scale" may also cause problems as noted below.

Note that Apple ignores numerous `<viewport>` specifications:

> Apple decided to ignore the declarations of user-scalable, minimum-scale, and maximum-scale, as of iOS 10.

<https://sitebulb.com/hints/mobile-friendly/the-viewport-meta-tag-has-a-minimum-scale-set/>

**Comment by plateaukao** [comment]
@dredmorbius this would be supported in next release. If you would like to try it first, you can install the nightly version on main page.

**Comment by plateaukao** [comment]
supported in 9.5.0
