### ISSUE TITLE
I can't find the history button anywhere 😔

### ISSUE THREAD

**Issue by shaikhsadi2** [plateaukao/einkbro#148]
I can't find the history button anywhere. That is, where can I find the websites that I am browsing in the form of history? 
![Screenshot_2022-07-25-00-04-36-82_5cd225ada6153df039aa0f4408fcc4ec](https://user-images.githubusercontent.com/94756026/180660109-7d4fedf1-01f9-4d5d-8de4-83eeb6765def.jpg)

**Comment by plateaukao** [comment]
It's a bit hidden.
Please click on tab count icon first (the icon with 1 in it)
![image](https://user-images.githubusercontent.com/4084738/180797393-5cac4a84-f641-47ce-bde2-594572408378.png)
And then, press the clock icon. Voila.
![image](https://user-images.githubusercontent.com/4084738/180797525-4ec96744-a123-489c-a0b4-0ad316d00c22.png)

**Comment by plateaukao** [comment]
Also, another quick way to bring up recent 5 histories, you can long press the "<" on the toolbar. :)
