### ISSUE TITLE
propublica.org web sites causes app hang or crash, "Can't load this URL: null" error

### ISSUE THREAD

**Issue by ziggyb1013** [plateaukao/einkbro#156]
I occasionally view propublica.org articles.

If you go to the front page, the site will often not completely load and will hang EInkBro. Sometimes you can still access EInkBro's settings, but none of the page links will work. EInkBro eventually crashes.

If you view an article, i.e. https://www.propublica.org/article/files-taxes-free-inflation-reduction-act

It will also not completely load, but you can still scroll most of the article but not all of it. Most of the bottom of the web page will be blank. I think, once you hit one of the ads lower in the article, it will also cause EInkBro to hang. Try to click anywhere, will occasionally throw the error, "Can't load this URL: null"

EinkBro: v9.5.0
Device: Boox Note Air (2022-06-21_20-34_3.2.3_b3d862)

**Comment by plateaukao** [comment]
@ziggyb1013 
It looks like something wrong with adblocking feature on this website.
You can turn off adblocking (by long pressing setting button, and disable it) when you need to browse this site.

**Comment by ziggyb1013** [comment]
Thanks. I usually send articles from there to Instapaper to read offline.

**Comment by ziggyb1013** [comment]
Confirmed that site loads fine with the Ad blocking disabled.

Also thanks for the hint about holding down the settings button to get quick access to the ad blocker.
