### ISSUE TITLE
Flashes and reloads page if users try to reach end of text input field

### ISSUE THREAD

**Issue by MarjaE2** [plateaukao/einkbro#159]
Case 1:

Trying to add to a search string. Tap on search input bar, right-arrow until it stops. Page reloads, still not at end, need to try again. And again. And can't get to the end. With a long search strning, the end o the string doesn't fit in the input bar, so the right arrow is the only way.

Case 2:

Tyiping in larger input field. Can't see the cursor because it's blinking, so only way to know it's at the end is to right-arrow again and again.

**Comment by plateaukao** [comment]
Hi @MarjaE2 
Could you provide video link  to demo the problems you met? I don't quite understand what you mean.

**Comment by MarjaE2** [comment]
Sorry, I don't have a suitable camera.

I think I've figured it out though-- while I'm trying to arrow over, the keyboard disappears, and my next tap hits the mobile/desktop mode icon, causing the page to reload.
