### ISSUE TITLE
YouTube background play issue

### ISSUE THREAD

**Issue by ixzh** [plateaukao/einkbro#164]
I toggled on background play and enabled "loading non-active tabs" in behavior setting, but YouTube video  kept playing in the background when it was the active tab. the moment I switched to another tab, the video paused. 

is the "loading non-active tab" meaning video will be playing even if the tab is not active? 

PS: there is a typo in the description: "loading the content" not "cotent".

**Comment by plateaukao** [comment]
@ixzh 
* loading non-active tabs: it only tries to load content; it's not for deciding whether video is continued or not in non-active tabs. Originally, as you said, the video will be stopped when the tab is not active anymore. But from v9.7.0 (just released), the non-active tab should keep playing video now.
* background play: it means when app is in the background, not tab is in the background.

Thanks for noticing the typo and report it. I will fix it in next release. :)

**Comment by ixzh** [comment]
👍

**Comment by ixzh** [comment]
with thanks!  it works perfectly now
