### ISSUE TITLE
can't open Tokopedia site

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#165]
Blocked WebView
https://www.tokopedia.com/

**Comment by plateaukao** [comment]
it works on my device. Please give more details.

**Comment by Kita2345** [comment]
instead of loading (https://www.tokopedia.com/) it redirects to (https://log.tokopedia.net/blocked-webview)

**Comment by plateaukao** [comment]
Hi, @Kita2345 
As it said, it's intended to block WebView usage on the site. And EinkBro is implemented in WebView component. I don't know how the website detected; so I don't know how to surpass this behavior. You may need to check with the website instead.

Also, I found that it's possible to browse the site correctly with some Onyx Eink devices. So, if you have other issues in the future, please also help to provide device information too. It would be very helpful to identify whether it's a generic issue or it's an issue specific to certain devices only.

**Comment by bagaspardanailham18** [comment]
I've just facing the same problem, are you already fix this issue? @plateaukao 
this issue only found on Android btw, but in iOS works fine

**Comment by plateaukao** [comment]
@bagaspardanailham18 
what device model are you using?
and which app version  are you using?
