### ISSUE TITLE
Does Not Launch on BOOX Nova 3 Color

### ISSUE THREAD

**Issue by noobww** [plateaukao/einkbro#166]
9.5.0 works great, but 9.6.0 and 9.7.0 does not launch. Nothing happens after tapping the app icon.

**Comment by plateaukao** [comment]
@noobww 
I tried v9.7.0 on my BOOX Nova 3 Color, and it can be launched without problems. I am afraid that may be something wrong with your current data. Could you try to open the built-in Neo Browser first, link to any website, and try to share that link to EinkBro?
In this way, it will try to launch EinkBro without trying to load all the saved tabs. That may be one of the reason why it can't be launched successfully.

**Comment by plateaukao** [comment]
close due to no further information

**Comment by noobww** [comment]
Backed-up data in 9.5.0 causes same issue on 9.8.0, which launches successfully without restoring the 9.5.0 backup.

**Comment by plateaukao** [comment]
@noobww sounds like it's related to something stored on v9.5.0.Good to know that clean install v9.8.0 works for you, and sorry for the backup troublesome.
