### ISSUE TITLE
Report: WebView ignores SSL Certificate errors and accept any SSL Certificate

### ISSUE THREAD

**Issue by licaon-kter** [plateaukao/einkbro#168]
9.7.0 F-Droid

"Base config is insecurely configured to permit clear text traffic to all domains." or "Insecure WebView Implementation. WebView ignores SSL Certificate errors and accept any SSL Certificate. This application is vulnerable to MITM attacks"

Ref: https://beta.pithus.org/report/f3315d547be5f3cce7b129b5c5d46f50a7d42e271627e4a2843f5a677e92d894

Ref: https://github.com/MobSF/owasp-mstg/blob/master/Document/0x05g-Testing-Network-Communication.md#webview-server-certificate-verification

Any thoughts?

**Comment by plateaukao** [comment]
Hi, @licaon-kter 

Thank you for providing the information.
As a browser, I think it's normal to permit clear text traffic to all domains. Or, do you know what domains should I block for clear text accessing?

And about SSL Certificate error scenario, in EinkBro, it does not accept the certificate directly for user. It will pop up a dialog to describe the SSL error, and ask user if they want to continue the website. This should also be a common handling for SSL Certificate error. If you know other open source browsers that have better implementation to be more secure, please let me know too. I would love to enhance the error handling. :)

https://github.com/plateaukao/einkbro/blob/986a5ef6999c7623ca63f1581467224b53eab766/app/src/main/java/info/plateaukao/einkbro/browser/NinjaWebViewClient.kt#L289-L307

**Comment by licaon-kter** [comment]
Not sure, looking at https://f-droid.org/en/packages/com.stoutner.privacybrowser.standard/ and the report is the same

**Comment by plateaukao** [comment]
@licaon-kter 
I checked privacy browser source codes, its implementation is similar to EinkBro:
1. allow clear text for all domain
![image](https://user-images.githubusercontent.com/4084738/191532211-24305d6c-b7c0-4b9b-853e-23eeafb83737.png)
2. popup dialog when receiving ssl error:
![image](https://user-images.githubusercontent.com/4084738/191532547-6e97269d-3cf9-4918-9613-4be3795f202c.png)

**Comment by plateaukao** [comment]
close due to no further information.
