### ISSUE TITLE
Set custom URL as Start Site

### ISSUE THREAD

**Issue by zetaomegagon** [plateaukao/einkbro#169]
Currently it only seems possible to set the starting site by navigating to it; then selecting set start site from the overflow menu.

I'd like to request a feature to add a custom Start Site, since some URLs can't be set by navigating to them. Example `https://en.m.wikipedia.org/wiki/Special:Random`

**Comment by plateaukao** [comment]
sounds great. I'll add this feature. Thanks for the suggestion.

**Comment by zetaomegagon** [comment]
Sorry, a little late with this reply but: Awesome Thanks for responding!

And keep up the good work!

(Side note: do you have any Android Dev resource recommendations? Maybe next time my feature request could help you out by being a pull request?)

Sep 22, 2022 01:18:26 Daniel Kao ***@***.***>:

**Comment by plateaukao** [comment]
Pull request would  always be welcomed. :) Last month til now, I'm busy with some writing competition. I'll work on it this weekend, I hope so .
