### ISSUE TITLE
Browser freeze when trying to download

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#173]
https://staktrace.github.io/moz-pages/fenix6089.html

**Comment by plateaukao** [comment]
I checked the url and found it's data url, not a real file to download. EinkBro's support for data url (`data:.....`) is not good. So, if you find sometimes EinkBro does not work well, please use other browsers to complete the task.


![image](https://user-images.githubusercontent.com/4084738/194801942-c2025f68-642a-4ef4-bed4-5c3cdfc447a2.png)
