### ISSUE TITLE
zhihu.com text going off the screen, refusing to wrap

### ISSUE THREAD

**Issue by caoyirui** [plateaukao/einkbro#188]
https://imgur.com/a/dqsyNh7

**Comment by plateaukao** [comment]
你可以試著到設置>操作行為/介面，打開 "總是啟用網頁放大功能"，然後回到知乎的畫面，用雙指把畫面縮小看看。

**Comment by caoyirui** [comment]
我在reddit.com就没有这个问题还有手机上的Safari浏览知乎文字也会自动wrap。有没可能EinkBro把知乎识别为桌面版的网页？但EinkBro的desktop
mode开和关都试过了，还是一样的看不见所有文字问题。

root cao ***@***.***>于2022年12月2日 周五上午10:29写道：

**Comment by plateaukao** [comment]
每個網站的撰寫方式不同，EinkBro 無法完全都考慮到。Safari 的實作跟 Chrome，或是微軟的 Edge 都不一樣，所以 Safari 上的呈現方式是無法拿來跟 Android 上的瀏覽器做比較的。

EinkBro 除非你有特別把它設定成要顯示桌面版，不然大部分是會被當成行動版顯示的。我在我的 BOOX Note 3 上看知乎的文章是正常的。

你可以檢查看看長按設定按鈕，看最下方的桌面模式是不是有不小心打開了。

![image](https://user-images.githubusercontent.com/4084738/205449569-128392a3-9865-45df-80e9-794ec41bce61.png)

**Comment by plateaukao** [comment]
另外，請多說明一下目前的 EinkBro 的版本，比較舊的版本可能會有些影響。

**Comment by caoyirui** [comment]
我用的是Boox Tab 8。我删除了EinkBro然后在GitHub下载了最新版本也确认了桌面模式没有打开，但还是文字不wrap。
https://imgur.com/a/MnHC5Wt

**Comment by plateaukao** [comment]
請問同樣的網頁，在 BOOX 內建的瀏覽器中，看起來效果是怎樣的呢

**Comment by caoyirui** [comment]
在 BOOX 內建的瀏覽器中也有同样的问题诶
https://imgur.com/a/w4PqLxU

**Comment by plateaukao** [comment]
@caoyirui 
那就應該是 BOOX 使用的 WebView 或是 BOOX 本身造成的，不是在 EinkBro 能修改的事。所以我先把這條 issue 關掉
