### ISSUE TITLE
Unable to login to Twitter

### ISSUE THREAD

**Issue by tcchuin** [plateaukao/einkbro#191]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Hisense a9
 - OS: android 1q
 - Browser wink to
 - Version 9.15.0

**Describe the bug**

Cannot login onto Twitter.
After I key in id and password, it just gets stuck on a blank page. Refreshing brings me back to unlogged in state
I do receive success login notifications via email and twitter notifications 

**To Reproduce**
Steps to reproduce the behavior.

Example description:
1. Go to Twitter.com
2. Login
3. Stuck at blank page 
4. Refreshing returns me to unlogged in state

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by plateaukao** [comment]
close because no further information.
