### ISSUE TITLE
"White Background" toggle does not work  on Mastodon sites

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/einkbro#193]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Onyx BOOX Max Lumi
 - OS: Android 10
 - Browser: EinkBro
 - Version: v9.15.0

**Describe the bug**

Toggling on "White Background" does not give dark-on-light page for Mastodon sites.

**To Reproduce**

Steps to reproduce the behavior.

Example description:
1. Go to <https://mastodon.social/>.  Website defaults to a dark white-on-black theme.
2. Open EinkBro controls via hamburger menu (lower right), select "White Background"
3. Website remains dark-mode (white-on-black theme).

**Expected behavior**

Expecteation is that website displays light mode (black-on-white) theme.

**Screenshots**

**Additional context**

Mastodon itself should support theme toggling, though there may be additional hints it could provide or follow which would improve interoperability with EinkBro.

I've opened a related issue on the Mastodon project page here:  <https://github.com/mastodon/mastodon/issues/22420>

**Comment by plateaukao** [comment]
@dredmorbius 
It looks like Mastodon's website is too complicated. I don't know how they set up their colors. So the mechanism in EinkBro does not work. As Mastodon documentation says, it has light theme. Please consider using it directly.
https://docs.joinmastodon.org/user/preferences/#theme

**Comment by dredmorbius** [comment]
@plateaukao Thanks, that's pretty much what I'd figured.

Just FYI, I _can_ toggle themes if I'm logged in to Mastoton.  I don't do that from my tablet (vain attempt to avoid timesucks), and there's no toggle available for public / anauthenticated visitors.

I see this as mostly Mastodon's problem.  Appreciate your looking at this.

Closing.
