### ISSUE TITLE
Custom url changed to ecosia

### ISSUE THREAD

**Issue by kogeletey** [plateaukao/einkbro#197]
**What device and app version are you using**
 - Device: Nokia 5.3
 - OS: Android 11
 - Browser EinkBro
 - Version 9.16.0

**Describe the bug**
When I try to find something, my custom search url replaced to ecosia

**To Reproduce**
1. Change custom url and its setting
2. Start search
3. Searches not through custom settings

**Expected behavior**
Search through my search engine specified in custom url setting

**Video**
[video showing bug](https://get.re128.net/ScreenRecording_20230102_101759.mp4)

**Comment by plateaukao** [comment]
@kogeletey 
Hi, thanks for reporting this issue. It will be fixed in next version.
For a temporary solution, you could purposely select **ecosia** as search engine in Settings; then, it will use your custom Search url settings now.

**Comment by kogeletey** [comment]
Thank you for fixing and looking so quickly, but already changed to ecosia and everything worked :+1:
