### ISSUE TITLE
Sometimes a new tab is rendered smaller

### ISSUE THREAD

**Issue by beelzebielsk** [plateaukao/einkbro#205]
Sometimes when I shut my device's screen off and on, the rendering of the page is too wide and goes off screen.

**What device and app version are you using**  
 - Device: Onyx BOOX Poke 2
 - OS: Android 9
 - Browser: Einkbro
 - Version 9.16.0

**Describe the bug**  
Sometimes when I open a new tab, the tab is shown shrinked into the top left corner of my screen. I can see the prior tab underneath it. Here's a screenshot:

![Screenshot_20230113-002113~2](https://user-images.githubusercontent.com/16908019/212734422-882b66ec-08e3-4e47-80e7-0e9a6acf7b31.png)

The red line shows roughly the visual size of the tab. While it looks smaller, clicking outside of the small tab still clicks on the small tab. And to click on something on the screen, I have to tap where it normally would be without the bug. This screenshot shows an example. The red arrows show where I have to  tap on the screen to interact with those two buttons.

![Screenshot_20230116-115546~2](https://user-images.githubusercontent.com/16908019/212734506-d53a58ba-d48d-4881-b421-056677e3a70e.png)

I don't think the website matters. It happened on several sites. This happens on my eink device. This has not always happened, I updated within a month from today and I don't know what the prior version was. But it started happening after that update. The buggy tab persists even if I change tabs. It doesn't effect other tabs if I switch to them. They remain at a normal size. It persists after a refresh. It persists if I visit a new site in the tab. If I close the browser and re-open it, the tab renders normally. I believe the size of the defective tab is always the same.

I haven't been able to reproduce this on my mobile phone which isn't an eink device.

**Mobile phone specs**  
 - Device: moto g(7) power
 - OS: Android 10
 - Browser: Einkbro
 - Version 9.16.0

**To Reproduce**  
Open a URL in a new tab from within the browser or open a link using the browser.

**Expected behavior**  
The tab should render at full size.

**Comment by plateaukao** [comment]
Please update to 9.17.0 or 9.18.0 and see if it works. I had a fix to solve similar issue on v9.17.0. If not, I’ll check again. Thanks for reporting the issue.

**Comment by beelzebielsk** [comment]
I updated to 9.18.0 on my eink device. It still happens.

**Comment by plateaukao** [comment]
@beelzebielsk 
Please try to download this zip file, and unzip it to install the apk to see if the issue is fixed.
https://nightly.link/plateaukao/einkbro/workflows/buid-app-workflow.yaml/main/app-release.apk.zip

**Comment by beelzebielsk** [comment]
I'm not able to install this on my devices. It just says something went wrong without further detail.

**Comment by plateaukao** [comment]
hm..then maybe you installed it from fdroid or Google Play Store. Please wait for next release. I'll  open this issue for now.

**Comment by beelzebielsk** [comment]
Yes I got it from F-Droid. I installed your version (by uninstalling mine). The problem still happens.

**Comment by plateaukao** [comment]
Please try the nightly zip again. This time it should work!
If not, I may need you to help record a video that shows in what specific circumstances it happens.

**Comment by plateaukao** [comment]
By the way, with latest version, you could backup bookmarks and settings to a zip. In case you want to install the version from fdroid again (for easier later version update), you could easily restore bookmarks and settings, and toolbar configurations.

**Comment by beelzebielsk** [comment]
It still happens. I found a way to reproduce the bug consistently:

1. Open Einkbro. If it was open prior (meaning it's in the recent apps list), close it first.
2. Visit a URL.
3. Lock the device and then unlock it.
4. The webpage should change. Everything should get a little bigger.
5. Open a new tab and visit any page
6. The tab should be small

I thought these bugs were separate and was going to report it later, but now it seems not. The font change doesn't happen on my phone. Only my e-ink device.

**Comment by beelzebielsk** [comment]
I do think your fix reduced the frequency of the bug.

**Comment by plateaukao** [comment]
It may be related to `Lock screen` is fullscreen, and you also turned on bottom navigation bar (which has back, home, and recent apps button). 
I, myself, do not lock my BOOX devices, and don't have bottom navigation bar now (may I know which firmware you are using now on Poke2?) so never encounter this issue.

I tried the steps you provided (and also setup lock screen) on my BOOX devices (Nova Air C, Note 3, poke 4S), and can't reproduce the issue now.

Also, did you tried to update WebView component to the latest one on your poke2?

**Comment by beelzebielsk** [comment]
Poke 2 firmware: `2022-12-06_17-32_3.3.1_bdf6080`

So I misspoke. When I said to lock the device, I just meant to hit the power button. Not to have a password or anything.

I don't think I updated the WebView. Is that the browser app? Do I need to use the play store to update it? I prefer to keep the play store off of this device.

I do have the bottom navigation bar active. I tried shutting it off. I was able to reproduce the bug still.

Can you elaborate on what "Lock screen is full screen" is? Is it still relevant if I don't lock the device?

**Comment by plateaukao** [comment]
If you did not set up password when hitting the power button, then it may not be related to what I just said.

`Android System WebView` is the Android built-in Web engine. That's what EinkBro App uses underlying (and so does Via, xBrowser, and most small browsers in Android).

It is updatable through Google Play Store. Google constantly fixes issues and enhance its security. You can check its version in BOOX Application tab, tap on top right menu icon, and tap Application Management, and tap the second item (Application), and tap top right menu button again, to show system applications.

Look for Android System WebView.
The screenshot shows mine: its version is 108.0.5359.128

![image](https://user-images.githubusercontent.com/4084738/214108584-45430662-833b-4ba3-8de7-a5fb62136534.png)

**Comment by beelzebielsk** [comment]
My webview version is `104.0.5112.97`. I wasn't able to find a way to update it without the play store, and when I tried to use the play store, I was told my device isn't Google protect certified. So I don't currently know how to update my webview.

I tried updating it without the play store by downloading an apk for it and manually installing it. It failed, saying app not installed at the end.

**Comment by dmitrijoseph** [comment]
I can reproduce the bug 100% by following the steps described above. 
I am on the newest version of Android System Webview  `111.0.55663.58` 
I am on an Onyx Boox Leaf 2. Basically makes this app unusable for me.

**Comment by beelzebielsk** [comment]
@dmitrijoseph May I ask what firmware you're on? I recently found out that a similar problem happens when I use the Libby app. This may be a problem with Onyx firmware.

@plateaukao Earlier you mentioned something about the gesture bar, since it came with the newest firmware. These problems happen whether the bar is activated or not. This is true for Libby, as well.

**Comment by dmitrijoseph** [comment]
Firmware: `2022-11-22_10-20_3.3.1_e4f27d41a`

**Comment by plateaukao** [comment]
@dmitrijoseph 
May I know if you enabled system navigation bar on the bottom of the screen? or you use system gesture to go back or go home?

**Comment by dmitrijoseph** [comment]
System navigation is disabled and I use gestures.

**Comment by beelzebielsk** [comment]
I reported the issue on the Onyx Boox reddit. This got their attention. They told me it should be fixed in firmware 3.3.2. Not sure when that will be released.

**Comment by plateaukao** [comment]
@beelzebielsk 
I already received firmware 3.3.2 update for my BOOX Nova Air C :D

**Comment by dmitrijoseph** [comment]
After updating to 3.3.2 I no longer experience the issue. Seems to have been a firmware issue from Boox.

**Comment by plateaukao** [comment]
this is fixed, hopefully.
