### ISSUE TITLE
After last update site appears blank

### ISSUE THREAD

**Issue by artelse** [plateaukao/einkbro#209]
**What device and app version are you using**
 - Version 9.19.0

**Describe the bug**
After the last update website [https://nos.nl](https://nos.nl) doesn't show, the page is completely blank.

**To Reproduce**
Visit site above.

**Comment by plateaukao** [comment]
@artelse 
It works on several on my android devices. Did you enter the site by using Google website? or do you input it directly from address bar?
If you do it from Google search results, sometimes, the first few items are Advertisement, and that will cause sites blank.

**Comment by artelse** [comment]
Weird, all sites I have bookmarked work except the one listed above. I tried downgrading but got an 'unknown error'. Uninstalled 9.19.0 and installed 9.18.0 and now the site works again.
