### ISSUE TITLE
Save tab doesn't work properly

### ISSUE THREAD

**Issue by islam2hamy** [plateaukao/einkbro#21]
V.8.8.2

Open 2 tabs
Close the browser from task manager for a while , may be 30 minit.

Open the browser
Only first tab is there

**Comment by islam2hamy** [comment]
p.s. : before closing the browser
Go to the first tab

**Comment by islam2hamy** [comment]
After closing the browser , lock the phone

**Comment by plateaukao** [comment]
Thanks for reporting this issue. I might found the root cause and had a fix.
But to make sure it really fix the issue without creating other side effects, I will use it for a while before releasing the fix.

**Comment by islam2hamy** [comment]
Fixed in 8.9.0
Nice work

**Comment by islam2hamy** [comment]
Sorry closed by mistake

**Comment by islam2hamy** [comment]
Please try this :
Opening link from (handy news reader)
Clear any opened tabs

**Comment by islam2hamy** [comment]
Or from any other app (whatsapp)

**Comment by islam2hamy** [comment]
Save tab is now working good , except opening url from external app , it clear all tabs

**Comment by gety9** [comment]
@islam2hamy 
is it still the issue for you with last releases?
I regularly open links from another app and it works fine.

**Comment by islam2hamy** [comment]
The

> @islam2hamy is it still the issue for you with last releases?

Yes

**Comment by plateaukao** [comment]
close for now.
