### ISSUE TITLE
Going "back" on a tab that was opened by "New  tab" returns a "No previous page!"

### ISSUE THREAD

**Issue by ziggyb1013** [plateaukao/einkbro#212]
Hello, I sort of understand the logic of this. If you go "back" on a page with no previous page, the "No previous page!" message makes sense.

However, my use case as been:
1. Open a new tab from a link, "New Tab (foreground)"
2. Finish reading the new tab.
3. "Back" to return to the first tab

Before it 9.20.0, eInkBro would, close the "new tab" and return to the previous tab and very seamless. I also do this on Safari in iOS and this behavior works the same way.

One of the reasons I did this, was that sometimes going to a link (from a news site or very large page), when you go "back" in the same tab, the page refreshes and you lose your place.

By opening a new tab, with the new link. The previous tab retains the page location and less likely to refresh while you're reading the new link.

Adding an option to not display, "No previous page!" and instead, close the tab and return to the previous tab would be great.

Thank you!

**Comment by plateaukao** [comment]
@ziggyb1013 
Will add an option to disable it. :)

**Comment by ziggyb1013** [comment]
Thank you!

**Comment by ziggyb1013** [comment]
Just installed 9.21.0 and the "old" behavior is back and it's glorious! Thank you!
