### ISSUE TITLE
URL with parameters adds a "=" at the end and makes parameter unusable

### ISSUE THREAD

**Issue by g-roi** [plateaukao/einkbro#213]
Version 9.19.0 with Samsung Galaxy S22, Android 13

Problem: URL with parameters adds a "=" or a "=null" at the end and makes the parameter unusable

Example 1:
URL with correct parameter: 
https://example.com?orf
translates to 
https://example.com?orf=  
shown in the URL field of Einkbro

Example 2:
https://example.com/rss.php?http://diepresse.com/rss/home  
translates to:
https://example.com/rss.php?http%3A%2F%2Fdiepresse.com%2Frss%2Fhome=null 
which of course cannot be opened.

**Comment by plateaukao** [comment]
I'll fix this issue in next version. 
However, it will only work when there's no tracking parameters are found.
If some tracking parameters are found, I'll use Kotlin's Uri to parse the url, and then, it will return that key with `=`.

**Comment by plateaukao** [comment]
fixed. please try it with 9.21.0
