### ISSUE TITLE
"White background" removes some contents on the google search page

### ISSUE THREAD

**Issue by searene** [plateaukao/einkbro#214]
Hi,

First of all, thank you for creating such a great web browser for eink devices! I use it daily and I really love it! I particularly love the "white background" option in it, but it doesn't work correctly on the google search page. It would be great if it could be fixed :) Here is some info you might find useful.

**What device and app version are you using**
 - Device: Boox Note3
 - OS: Android 10
 - Browser EinkBro
 - Version 9.5.0

**Describe the bug**
When "White background" is enabled, some contents on the google search page cannot be seen. Here are two images representing the search result when the "white background" option is disabled / enabled:

"White background" disabled:

![normal](https://user-images.githubusercontent.com/3351317/218300090-80e27480-8d02-480a-a074-c98092a98a8c.png)

"White background" enabled:

![white background](https://user-images.githubusercontent.com/3351317/218300109-b60e79b7-48ab-4d9f-8cc7-cbd75ed2e252.png)

**To Reproduce**
1. Open EinkBro
2. Open www.google.com
3. Search "google play" on it
4. Enable "white background" in the toolbar
5. Notice that some contents on the page are whitened out.

**Expected behavior**
All the texts should be seen clearly on the page, especially when the texts are dark enough.

**Comment by plateaukao** [comment]
@searene 
Hi, thank you for reporting this symptom to me. 
In fact, white background feature works best when it's used on websites that have black background and white text color. As for other sites that have normal text color and background, it may not work normally. 

If your intention is to make all texts look more clear in normal websites, you can upgrade to 9.20.0.  In this version, a new function (black text) is added next to (white background) button in action menu. It will try to make all texts pure black, without modifying other parts of the web.

**Comment by searene** [comment]
Hi @plateaukao,

I just updated EinkBro and tried the "black font" feature, it worked just as expected. Thanks for creating such a great app!
