### ISSUE TITLE
eink reader use pageup/down button 

### ISSUE THREAD

**Issue by jackjin-cn** [plateaukao/einkbro#222]
einkbro is a good  browser for eindkreader.thanks for your work.
I hava boox leaf2 ,it's has pageup/down buttons ,in einkbro ,they worked .

but there is a problem,when I use  touch area to up /down pages, speed is so fast,worked immediately,
if I use pageup/down buttons,page slided slowly,need more times than use touch area.
so I suggest that pageup/down buttons can slide pages as fast as using touch area。
my english is not good,I hope than you can understand my problem.

**Comment by plateaukao** [comment]
Hi, @jackjin-cn 
You can try to toggle volume-key page up/down feature by long pressing Setting button, 
and in BOOX leaf2, button settings, configure EinkBro to act as volume keys for its physical pageup/down button.

On my BOOX Nova AirC, I can use physical pageup/down buttons just like touch area behavior in EinkBro.

**Comment by jackjin-cn** [comment]
thanks, I follwow you suggestin，it's worked。
