### ISSUE TITLE
Tabs show the previous web page's favicon icon

### ISSUE THREAD

**Issue by ziggyb1013** [plateaukao/einkbro#224]
Using EinkBro v9.22.0 on Boox Note Air (OS Version 2022-11-24_17-36_3.3.1)
Minor issue, but seems weird.

1. Open a new tab and load a page, such as https://www.theverge.com
2. The favicon is the correct one for the web site (stylized V logo)
3. Open bookmarks and load another page, such as https://arstechnica.com
4. The favicon is still the stylized V from the previous web site
5. Open bookmarks and load https://www.theverge.com
6. Now the favicon is showing the one for arstechnica.com (ars logo)

Issue seems repeatable.

![01](https://user-images.githubusercontent.com/111400148/226060464-0cb2c5b8-04e4-4c0f-a679-70eb4a657e02.jpg)
![02](https://user-images.githubusercontent.com/111400148/226060477-7f200c4c-88d5-4164-b739-991035dd100b.jpg)
![03](https://user-images.githubusercontent.com/111400148/226060481-8c135625-6a8a-4fe3-9ee7-a40a1adce160.jpg)

**Comment by plateaukao** [comment]
@ziggyb1013 
Please try version 9.23.0.
The issue should have been fixed.
