### ISSUE TITLE
Home URL not working

### ISSUE THREAD

**Issue by Cwpute** [plateaukao/einkbro#227]
Ever since a couple updates (3 max) my custom home URL hasn't worked as intended. In previous versions, it would open the home URL on startup… but it doesn't anymore. It just opens the last open tabs instead.
Is there a behavior i'm not understanding here ? is there something i checked which i shouldn't have ? the options are pretty hard to navigate through, it is not always clear which triggers each menu hides.

**Comment by plateaukao** [comment]
@Cwpute 
Sorry for the confusion. You can go to Settings > Behavior , and uncheck "Save Tabs".
In this way, next time you relaunch EinkBro, it won't show previous opened tabs.

**Comment by Cwpute** [comment]
okay yes, it seems i didn't see this one option.
On a side note, the settings menu would probably need some reorganization and/or clarificatiwn, i never  know where to search for what information.

**Comment by plateaukao** [comment]
@Cwpute 
Thanks for the suggestion. If you have any idea how to arrange the settings better, or you find any app that did a better job with so many options, I would love to consider it.

**Comment by Cwpute** [comment]
working on it 👍
