### ISSUE TITLE
[Feature Request] Share to Pocket uses built-in share if Pocket App is installed

### ISSUE THREAD

**Issue by winstonma** [plateaukao/einkbro#229]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Douglas
 - OS: Android 13
 - EinkBro Version 10.0.0

**Describe the bug**
Actually it is not a bug. I install both Pocket and Einkbro on my device and would like to know if it is possible that the device would trigger the Pocket share if Pocket App is found (Just try to avoid re-login 😅). Not sure [this old method](https://stackoverflow.com/questions/16108356/share-to-pocket) or [this function](https://github.com/cstdr/cstdr.ningningcat/blob/c6d6e18436a52f83f364fa83c264910041e017ab/src/cstdr/ningningcat/util/ShareUtil.java#L62) still works.

It's just nice to have features =)

**To Reproduce**
Steps to reproduce the behavior.

Example description:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by plateaukao** [comment]
@winstonma 
Should work now in snapshot build (maybe 10 minutes later).

**Comment by winstonma** [comment]
Sorry to interrupt.

I am reading [How I hacked around the Pocket app to cut down on my browser tabs.](https://chrisguzman.svbtle.com/i-hacked-the-pocket-app-to-cut-down-on-tabs) and it seems the sharing the url to `com.ideashower.readitlater.activity.AddActivity` wouldn't go to Pocket App.

Not sure if it is worth to try 😅 and sorry to have so many request

**Comment by winstonma** [comment]
Thanks it works on my Android 10 tablet but it doesn't work on my Android 13 phone. After surfing checking the logcat

```
04-14 11:16:29.716  1492  2809 W PackageManager: Intent does not match component's intent filter: Intent { flg=0x10000000 cmp=com.ideashower.readitlater.pro/com.ideashower.readitlater.activity.AddActivity (has extras) }
04-14 11:16:29.716  1492  2809 W PackageManager: Access blocked: ComponentInfo{com.ideashower.readitlater.pro/com.ideashower.readitlater.activity.AddActivity}
04-14 11:16:29.716  1492  2809 I ActivityTaskManager: START u0 {flg=0x10000000 cmp=com.ideashower.readitlater.pro/com.ideashower.readitlater.activity.AddActivity (has extras)} from uid 10327
04-14 11:16:29.717 27398 27398 W System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ideashower.readitlater.pro/com.ideashower.readitlater.activity.AddActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
```

Google showed me this article [Android 13 针对 Intent filters 安全的再加强](https://blog.csdn.net/allisonchen/article/details/124831226). It seems to me that this is an Android 13 thing and it seems that it is data of the intent filter need to be specified.

I then downloaded the Pocket APK and extract AndroidManifest.xml using [apktool](https://ibotpeaches.github.io/Apktool/). After opening the XML file I focused on the AddActivity and find it's corresponding intent-filter.

```
            <intent-filter android:label="@string/nm_add_to_ril">
                <action android:name="android.intent.action.SEND"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:mimeType="text/plain"/>
            </intent-filter>
            <intent-filter android:autoVerify="true" android:label="@string/nm_add_to_ril">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="http"/>
                <data android:scheme="https"/>
                <data android:host="getpocket.com"/>
                <data android:pathPrefix="/save"/>
                <data android:pathPrefix="/edit"/>
            </intent-filter>
```

The whole AndroidManifest.xml file is attached for your reference ([AndroidManifest.zip](https://github.com/plateaukao/einkbro/files/11228633/AndroidManifest.zip), please rename extension to .xml)

Sorry again

**Comment by plateaukao** [comment]
@winstonma 
Please try latest build again. I did some modification, and it works on my Android 13 device.

**Comment by winstonma** [comment]
Thanks you very much!!!

**Comment by dredmorbius** [comment]
Oh, nice!  I just saw this feature after checking recent Github issues.

This saves a few taps when saving articles, which I do a lot.

**Comment by winstonma** [comment]
Yep. I would also like to see if it is possible to implement **Save Link to Pocket** feature so I could save some webpage to pocket without opening it (yes I am too lazy).

![image](https://user-images.githubusercontent.com/1215090/233527280-8f149011-b798-4bd9-89a0-a3d01a32f9b9.png)
