### ISSUE TITLE
[BUG] ChatGpt and/or Translate dialog.

### ISSUE THREAD

**Issue by ckysmrn** [plateaukao/einkbro#233]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device:  Xiomi Mi A2 Lite
 - OS: Android 9 
 - EinkBro Version: 10.2.0. 

**Describe the bug**
ChatGpt and/or Translate just showing blank dialog.

**To Reproduce**
1. Selecting text.
2. Showing Dialog.
3. Click ChatGpt/Translate icon on dialog.
4. Showing new blank dialog

**Expected behavior**
What ever but not blank dialog.

**Screenshots**
-  Translate
![Screenshot_20230416-195908](https://user-images.githubusercontent.com/116737642/232316088-04149310-a0d6-4571-b40b-1ad18c0b4d64.png)

- ChatGpt
![Screenshot_20230416-204736](https://user-images.githubusercontent.com/116737642/232316122-08fd8ac7-f1fc-4028-950d-0b580ee7f4b0.png)

**Comment by plateaukao** [comment]
@ckysmrn 
Try disable dark mode, it should work; or download the latest zip; this issue is already fixed but not yet released.

**Comment by ckysmrn** [comment]
@plateaukao 
Thank a lot for your job, now its work as expected..
And about "dark mode"  I have disabled in **Settings > UI > Support Dark Mode**, but theme still dark and not light/white.

Screenshoot:
![Screenshot_20230417-030223](https://user-images.githubusercontent.com/116737642/232339184-8525e075-e4ae-40af-a92f-cd893fbb62d3.png)

**FYI:**
"Mode Gelap" is indonesian language stand for "dark mode".
"dinonaktifkan" is indonesian language stand for "disable".

**Comment by ckysmrn** [comment]
> @ckysmrn Try disable dark mode, it should work; or download the latest zip; this issue is already fixed but not yet released.

@plateaukao 
btw translate work better
but chatgpt make einkbro force close.
**FYI: i was setup openai key in settings**

**Comment by plateaukao** [comment]
As I know, there's  no dark mode for Android. Did you use Xiaomi's own dark mode feature?

As for force close, in what step it fails?

**Comment by ckysmrn** [comment]
> As I know, there's no dark mode for Android. Did you use Xiaomi's own dark mode feature?

My Phone haven't dark mode, only quick settings with dark style.
My Phone (Xiaomi Mi A2 Lite)  bring SystemUI from G++gle named AndroidOne UI not MIUI from Xiaomi so I haven't Xiaomi/MIUI feature.

**FYI**: 

AndroidOne is stock android with G++gle Bloatware smilar to G++gle Pixel.

But.. first time installing einkbro, I get dark style in apps by default, look like screenshot I've share.

> As for force close, in what step it fails?

Sometime force close, when I selecting text and click icon ChatGpt in showed dialog, but sometime just showing dialog with triple dot like "..."

**Comment by plateaukao** [comment]
triple dot is shown when chatgpt api is requested underlying. when api succeeds, content response will be shown instead. Is your OpenAIAPI key working in other scenarios? for example in other services or apps?

**Comment by ckysmrn** [comment]
> triple dot is shown when chatgpt api is requested underlying. when api succeeds, content response will be shown instead. Is your OpenAIAPI key working in other scenarios? for example in other services or apps?

I hasn't  testing my OpenAI Api on other apps.

**Comment by plateaukao** [comment]
add more error handling for gpt integration.
