### ISSUE TITLE
Some websites render as blank white page with adblock enabled

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/einkbro#234]
**What device and app version are you using**
 - Device:  Onyx BOOX Max Lumi
 - OS: Android 10
 - EinkBro Version: 10.0.0

**Describe the bug**
When browsing with adblock enabled, _some_ but **NOT** _all_ websites appear as blank white pages.

Two domains which render blank pages are https://ft.com/ (Financial Times) and https://sfchroncle.com/ (San Francisco Chronicle).

Toggling adblock off renders the sites as expected.

**To Reproduce**
Steps to reproduce the behavior.

1. Toggle adblock on.
2. Visit <https://ft.com/> or <https://sfchronicle.com/>
3. Blank white page is presented.
4. Toggle adblock off and wait for page to automatically reload.
5. Site appears as expected.

**Expected behavior**
Full site (other than ads) should appear when adblock is enabled.

**Screenshots**
None.

**Additional context**
First noted in an earlier 9.x release circa January / February.

**Comment by plateaukao** [comment]
both sites render fine on my boox note3 with v10.3.0.

Did you change the adblock url?

**Comment by dredmorbius** [comment]
Not that I'm aware.

Present value is:

<https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts>

(Under Settings -> Start Control -> Adblock list url)

**Comment by dredmorbius** [comment]
... though I'm running behind a Turris Omnia (OpenWRT) router with its own adblock DNS-based URL list.  Note that when I disable the **Einkbro** adblock, however, both sites _do_ load.

That there might be an interaction between the two is a possibility, though it seems unlikely.  Cue DNS haiku...

**Comment by dredmorbius** [comment]
Latest Einkbro version I find on Fdroid is 10.2.0.  I'm updating as I write this ...

OK, updated.  Issue is still present w/ 10.2.0.

**Comment by plateaukao** [comment]
may I know how you access these two sites?  Do you access them from bookmark, or type in the url in address bar , or from some website that contains the link?

**Comment by dredmorbius** [comment]
All of the above.

Directly typed-in URL, bookmark (probably most often, usually after typing in a partial URL and selecting from the presented set of history + bookmark matches), or links from other pages (same or different sites).

Behaviour is consistent among any of these methods.

**Comment by plateaukao** [comment]
the last thing you could try is to add the sites into whitelist. please long press menu icon, and click on the pen icon next to adblock toggle. Add ft.com and the other one. restart app and see if it works.

**Comment by dredmorbius** [comment]
Right, I'd thought of doing that.

I've just added "ft.com" which solves the page-not-loading problem, but isn't really a fix for viewing pages whilst blocking ads.

(It's not clear that the whitelist is domains only rather than protocol+domain.  So:  "ft.com", not "https://ft.com".  Though the ability to individually delete entries is useful.  I remember when that didn't exist.  Seems I've got a bunch of protocol-specified entries in my JS whitelist which I need to replace as well...)

**Comment by plateaukao** [comment]
looks like I need to add more descriptions for the feature. :)
You could leave as what you already added. I could do some parsing on the whitelist before applying them.

**Comment by plateaukao** [comment]
now it should work.

**Comment by dredmorbius** [comment]
The issue still persists for me.

Checking on 10.4.1 ...

<https://ft.com> still renders blank when adblock is enabled (I've also cleared the adblock whitelist entry, content _did_ appear with an entry for ft.com on the whitelist).

<https://sfchronicle.com> also blank.

10.5.0 is on F-Droid.  I'm updating as I write this ... and blank pages for both sites using that version as well.

If there's a more recent version I'll try that when it's available on F-Droid.
