### ISSUE TITLE
Frequent browser crashes opening new tabs or editing URLs

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/einkbro#235]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Onyx BOOX Max Lumi
 - OS: Android 10
 - EinkBro Version: 10.0.0

**Describe the bug**
Einkbro frequently crashes and dumps to device Home screen when opening new tab or directly editing URL.

This is intermittent and ... as I'm writing this at the moment, I'm unable to reproduce this myself having just quit and re-started Einkbro.  I'm filing this as an advisory issue in the event others are seeing similar issues, but **until I can reproduce it myself, closing as "cannot reproduce" is acceptable.**

**To Reproduce**
Steps to reproduce the behavior.

The bug seems intermittent and may not be triggered immediately within a browsing session.

1. Open browser.
2. Open a website, follow 2--3 links.
3. Either press the '+' toolbar button to open a new tab **OR** select the URL ("Title") to edit / enter a URL.
4. Browser immediately crashes and dumps back to the device Home screen.
5. On re-opening browser, editing URL or opening a new tab is generally successful.

**Expected behavior**

New tab should appear or URL should be edited / opened, without browser crashing.

**Screenshots**

None.

**Additional context**

This behaviour began immediately after updating to v. 10.0.0.

I'm generally starting with an extant session and  several open tabs.  I'm not sure what specifically is triggering this issue, and as noted, can't reproduce it myself at the moment, though it was occurring frequently yesterday.  🤷

**Comment by dredmorbius** [comment]
Updating:  I'm revoking "closing as cannot reproduce" statement above.  Issue is intermittent, but definitely present.

I'm still not sure exactly how this gets triggered, but it's happening _a lot_ (got an Android notification of frequent crashing for Einkbro earlier today), and it's definitely crossed a perception threshold for me...

Typically seems to occur after switching back to Einkbro and opening an additional tab or two (via links), after which '+' or URL edit prompt a crash.

Other recent changes:  applied Onyx 2023-04-17 and 2023-04-20 updates over the past few days.  The Einkbro issue appeared after I'd applied both the '17 Onyx firmware upgrade _and_ the Einkbro 10.0.0 App update.  The possibility that there's an Onyx issue does exist.

**Comment by plateaukao** [comment]
In latest built zip, I tried to fix several crash issues reported on Google Play Store console. You could download it in Readme and see if it helps. 

Personally, I don't encounter crashes often although I also creat tabs or edit url often on all my devices (more than 5) So it's hard to debug this issue.

**Comment by dredmorbius** [comment]
Sorry, what is "download it in Readme"?

And what's the version for that update?

FDroid now has 10.3.0, I'm installing that now...

--
Edward Morbius ***@***.***)
Dr. Edward Morbius's Lair of the Id
https://dredmorbius.reddit.com

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by dredmorbius** [comment]
Ah, thanks!

--
Edward Morbius ***@***.***)
Dr. Edward Morbius's Lair of the Id
https://dredmorbius.reddit.com

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by dredmorbius** [comment]
So ... tried to install snapshot, Onyx's Android installer won't allow it, for reasons unknown.

I did take a look at the contents though, and have been playing with the readability.css which relates to #33 (also updated).  I can't test on-device given that I can't install the package, however 😦

**Comment by plateaukao** [comment]
The signing key is different between the snapshot on github, and the one you used to install from F-droid. So you'll have to wait until I have new version for F-droid.

v10.4.0 mistakenly using old version number in codes, so F-droid won't release the same version.

**Comment by dredmorbius** [comment]
Thanks, will do.

The crashes are ... quite frequent now. If there's any way for me to generate / send a crash report, and if that would help, I'd like to know how.

--
Edward Morbius ***@***.***)
Dr. Edward Morbius's Lair of the Id
https://dredmorbius.reddit.com

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by plateaukao** [comment]
with fdroid's version. the crash logs are not helpful. If you could install EinkBro from Google Play Store, if it crashes, thr crash logs will be uploaded to Google console automatically, so that I may take a look at why it happens. 

Also, you could goto settings > Start control to turn off periodically update adblock list. that may be one of the reason too.

**Comment by plateaukao** [comment]
please open it again if it still happens with latest version.

**Comment by dredmorbius** [comment]
I'd noticed no crashes since updating to 10.4.1.

I've just updated to 10.5.0 (within the past 5 minutes), and ... so far so good.

Keep the issue closed, I'll update / open a new issue if I start seeing the issue again.

Thanks!
