### ISSUE TITLE
Wikipedia desktop mode is gone in 10.3.0? was ok on 9.19.0

### ISSUE THREAD

**Issue by jindamvani** [plateaukao/einkbro#239]
@plateaukao 
open https://te.m.wikipedia.org/wiki/%E0%B0%B5%E0%B0%BF%E0%B0%9C%E0%B0%AF%E0%B1%87%E0%B0%82%E0%B0%A6%E0%B1%8D%E0%B0%B0_%E0%B0%B8%E0%B0%B0%E0%B0%B8%E0%B1%8D%E0%B0%B5%E0%B0%A4%E0%B0%BF

* enable desktop mode in settings
* click _**desktop**_ at bottom of above given page

* layout has gone

it is ok 9.19.0
not ok 10.3.0

**v 9.19.0 screenshots**
![9191](https://user-images.githubusercontent.com/131695520/234061698-1c099092-2f98-4e4b-8ead-de220bd5797d.png)
![9192](https://user-images.githubusercontent.com/131695520/234061756-a1db921b-2e8c-4711-9233-65db9d48351e.png)

**v 10.3.0 screenshots**
![1031](https://user-images.githubusercontent.com/131695520/234061898-a63c9d93-078c-465e-b6b5-9ae4e957d968.png)
![1032](https://user-images.githubusercontent.com/131695520/234061930-0628fb5a-68f2-424b-9b72-a1cc982829d4.png)

**Comment by plateaukao** [comment]
@jindamvani 
Thank you for pointing out this issue. I added enable Zoom feature from v10.1.0.
And this feature caused normal desktop web layout to be shrunk to device width.

In next version, when desktop mode is enabled, I'll expand the web width, so that normal desktop content can be displayed.
