### ISSUE TITLE
a rule in ```AdGuard Base filter``` is not working

### ISSUE THREAD

**Issue by Apaaja20** [plateaukao/einkbro#242]
**This rule doesn't work**:

```j
/^https?:\/\/(?:[a-z]{2}\.)?[0-9a-z]{7,16}\.[a-z]{3,7}\/[a-z](?=[a-z]{0,25}[0-9A-Z])[0-9a-zA-Z]{3,26}\/(?:[1-6]\d{4}|[3-9]\d{3})\??(?:_=\d+|v=\d)?$/$subdocument,script,xmlhttprequest,third-party,match-case
```

**Steps to reproduce**

1. Add [AdGuard Base filter](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt)
2. Go to https://truyentieuthuyet.vn/truyen-chu-ta-chi-muon-an-tinh-lam-cau-dao-ben-trong-nguoi/

 ‌Actual result	Expected result
 ![Actual result](https://user-images.githubusercontent.com/74956696/232984081-6ce377e6-44c6-42c1-b37a-e88bcb1f6985.jpg)	![Expected result](https://user-images.githubusercontent.com/74956696/232984156-17c04be9-7ec8-4675-bcdb-85d15fcc36a2.jpg)

**Comment by plateaukao** [comment]
Where did you add the filter? currently EinkBro only supports normal host name list. It does not support regex format.

**Comment by Apaaja20** [comment]
Adblock list url

Pada Kamis, 27 April 2023, Daniel Kao ***@***.***> menulis:

**Comment by plateaukao** [comment]
@Apaaja20 
Please use formats like what's presented in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts.
Other than this format, it's not supported, and that may be why the app is crash when launching. Please uninstall EinkBro and re-install it to use similar source that has the same format.

**Comment by Apaaja20** [comment]
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt

**Comment by plateaukao** [comment]
The one you provided is not supported.
