### ISSUE TITLE
Error landing page when navigating to Economist.com

### ISSUE THREAD

**Issue by craigcullum** [plateaukao/einkbro#247]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Book Leaf 1
 - OS: Android 10
 - EinkBro Version: 10.4.1

**Describe the bug**
When navigating to economist.com, the website displays a landing page that says "Our apologies. An error seems to have occurred."

**To Reproduce**
Navigate to economist.com

Example description:
1. Go to economist.com

**Expected behavior**
The website homepage to be displayed, which is the case when using Neobrowser

**Comment by plateaukao** [comment]
@craigcullum 
It works fine on all my BOOX devices.
Did you set any different settings? Or, could you try to use other network?
Or could you give me any specific economist.com url that would fail?

Also, you could try to disable adblocking by long clicking on setting icon, and uncheck adblock.
Some said it might be the cause:
https://news.ycombinator.com/item?id=27177605

**Comment by plateaukao** [comment]
Here's another article related to the issue: https://www.reddit.com/r/theeconomist/comments/jcgrlj/blocked_from_the_economist_magazine/

**Comment by plateaukao** [comment]
If it happens because you try to bypass paywall, please use other browsers that are good or suitable for this purpose.
