### ISSUE TITLE
Issues with Twitter.com

### ISSUE THREAD

**Issue by tcchuin** [plateaukao/einkbro#248]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Hisense a9
 - OS: android 11
 - EinkBro Version v10.5

**Describe the bug**
When white background is enabled, there is a white bar right below the top bar, blocking the content 

Specified font is not used, font size changing works however.
**To Reproduce**
Steps to reproduce the behavior.

Example description:

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/20945080/237012366-305da08b-c468-40fd-b812-cc0e0665b81e.jpeg)If applicable, add screenshots to help explain your problem.

**Additional context**

**Comment by plateaukao** [comment]
@tcchuin 
please disable white background effect on twitter, since it already has white background by default.
Applying white background on it will have unexpected behavior as you observe.

**Comment by plateaukao** [comment]
If you just want to have blacker text, you can use black font instead; it won't try to change any block color, and potentially make things worse.

**Comment by tcchuin** [comment]
> If you just want to have blacker text, you can use black font instead; it won't try to change any block color, and potentially make things worse.

I switch between other pages that would benefit from white background often, and would be good if I don't have to switch the. White background mode everytime I change tabs 

Aside from the white background issue there's also font changing not working on Twitter, is there a way to fix it?

Thank you very much

**Comment by plateaukao** [comment]
For now, white background works as expected.
I'll consider add per site white background configuration.
