### ISSUE TITLE
Custom font not applied on some website

### ISSUE THREAD

**Issue by tcchuin** [plateaukao/einkbro#257]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Hisense a9, boox tab 8
 - OS: android 11
 - EinkBro Version 10.6.3

**Describe the bug**

Custom font is not applied on some website, defaulting to system font.

**To Reproduce**
Steps to reproduce the behavior.

Example description:
1. Go to Twitter.com
2. Click on setting
3. Change font to 3rd party font 
4. System font is being used (I.e. website font cannot be changed unless the device allows changing of system font)

**Expected behavior**
The third party font is applied 

**Screenshots**

**Additional context**

**Comment by plateaukao** [comment]
Hi @tcchuin 
Thank you for reporting this issue. I am aware of this issue, however I don't know how to resolve it. This is due to specific way of setting fonts in some websites. :) If one day I found out a solution, I will fix it as soon as possible.

**Comment by plateaukao** [comment]
@tcchuin 
This commit might help font changing more often succeeds. https://github.com/plateaukao/einkbro/commit/8503cf50f1ce339ef40224ce6c10b8c57589da19

**Comment by CR0CKER** [comment]
I'd love to see this fixed also.
