### ISSUE TITLE
go back not work when redirect happens

### ISSUE THREAD

**Issue by bibu2651** [plateaukao/einkbro#260]
sometimes when we click go back but can't get back because some site using redirect. I try to fix the problem by changing line 111 in NinjiaWebViewClient.kt like the following:

==========================================
        if (url.startsWith("http")) {
            // webView.loadUrl(url, ninjaWebView.requestHeaders)
            // return true

            // remark two lines above, and return false to let webkit handle go back, who can
            // go back to the correct page
            return false
        }
==========================================

it works for me

**Comment by plateaukao** [comment]
thanks for the information. Could you provide what websites you have verified?

**Comment by bibu2651** [comment]
1. open www.baidu.com
2. search apple
3. open apple official website in search result
4. when apple website loaded, click back, the page reloaded but still show apple site
