### ISSUE TITLE
[Feature request] Text selection and links through ChatGPT intergration

### ISSUE THREAD

**Issue by Inkapa** [plateaukao/einkbro#263]
### Originally discussed in https://github.com/plateaukao/einkbro/discussions/259
I've decided to create an issue from the discussion post above, because I wasn't sure that you saw it. I also feel like it could fit as an issue (especially links not being clickable)

<div type='discussions-op-text'>

<sup>Originally posted by **Inkapa** June  4, 2023</sup>
Hello,

I've been using the new chatGPT integration on EinkBro, and it's definitely promising. 

In my current use case I've configured the prompt settings to give me a detailed explanation of whatever text I select and I've asked it to always finish by linking sources and additional reading material relating to the matter at hand, as a way to proofread the information it gives me.

However as of now, I can't actually click the links or select any of the text that's displayed in the ChatGPT popup, it'd be a nice improvement to be able to directly open the links ChatGPT gives me in a new tab and to be able to select (and copy) parts of the generated text.</div>

Moving the window could be relegated to a button or a draggable header

**Comment by plateaukao** [comment]
afaik, the links provided by chatgpt do not work.
