### ISSUE TITLE
E-Ink Bro loosing tabs when opening links from other applications.

### ISSUE THREAD

**Issue by dotancohen** [plateaukao/einkbro#266]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Boox Note Air 2
 - OS: Android 11
 - EinkBro Version: 10.8.1

**Describe the bug**
I'll often have a few tabs open in E-Ink Bro. But when I click a link in e.g. Telegram or Pocket to open it in my default browser (E-Ink Bro), E-Ink Bro looses all other tabs and shows only the single new tab. I have found no setting to disable this behaviour, nor to restore the old tabs (other than the History).

**To Reproduce**

Example description:
1. Set E-Ink Bro as default browser.
2. Open three tabs in E-Ink Bro.
3. Add a link in Telegram or another app.
4. Click the link.
5. See that E-Ink Bro now has only a single tab open.

**Expected behavior**
I expect that there would now be _four_ tabs open: The three original tabs and a fourth tab which corresponds to the clicked link.

**Additional context**
Issue confirmed by another user [here](https://www.reddit.com/r/eink/comments/14jkzlt/eink_bro_loosing_tabs_when_opening_links_from/).

**Comment by plateaukao** [comment]
@dotancohen 
Thanks for reporting this issue. I'll look into it.

**Comment by dotancohen** [comment]
Thank you!
