### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [plateaukao/einkbro#267]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4560889506#L430

ref: https://github.com/plateaukao/einkbro/blob/v10.9.0/app/build.gradle#L20

Can you have versionName as static back just before Tagging? Since we build from a Tag there's no new info to gain if we add the timestamp, and this breaks autoupdates etc

ref: https://gitlab.com/fdroid/fdroiddata/-/commit/deae0da736d0028a0ba8deed7a4b2ab6d44933e9

**Comment by plateaukao** [comment]
@licaon-kter 
Got it, I will rollback to original naming for release build.
Thank you for pointing this out.
