### ISSUE TITLE
The new tab behavior only displays the srart input URL

### ISSUE THREAD

**Issue by chwt163** [plateaukao/einkbro#268]
Neither the "show home" nor "show bookmarks" options take effect. Each new tab displays "srart input url".

 - Device: huawei AL20
 - OS: android10
 - vebview：113
 - EinkBro Version 10.9.0

**Comment by chwt163** [comment]
I found the reason, I have to use the new tab button in the toolbar to display the home page to take effect. If you use the New Tab button in Tab Preview, only the input URL will be displayed. 
It's just that I don't really like that the toolbar has too many buttons, and hopefully the behavior of the new tab button in two different positions is the same.

**Comment by plateaukao** [comment]
thanks for the information. I'll align the behavior for these two buttons to follow setting.
