### ISSUE TITLE
Sometimes page up/down action does not work on feedly.com

### ISSUE THREAD

**Issue by bubbleguuum** [plateaukao/einkbro#271]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Boox Page
 - OS: Android 11
 - EinkBro Version: 10.10.0

**Describe the bug**
On feedly.com, the page up/down actions trigerred either by the hardware buttons or the dedicated area on screen (when that feature is active) do not work. It works fine on other web sites.

**To Reproduce**
- go to feedly.com
- unfortunately, it requires login which can be done quickly using existing Google or other account
- display a feed with articles
- use the hardware button of the Boox Page to go to next/prev page or tap the screen for the same functionality
=> It does not work (does nothing)

Sometimes it does work though (for a while until it doesn't, especially if reloading the page), and I've been unable to find a 100% reprod pattern.
This web site (feedly.com) has keyboard shortcuts that can be  displayed with the "?" icon with a circle and I wonder if something there do no get in the way.

**Comment by bubbleguuum** [comment]
There's a workaround for this issue. Prev/next page actions works after tapping the "..." button (below the icons at the top right, see attached screenshot) and dismissing that menu. So it looks to me that the main feed frame does not have the focus for key events and showing/dismissing that menu give it the focus.
![Screenshot_20230721-213454](https://github.com/plateaukao/einkbro/assets/761164/c7437296-09f6-4033-ab82-bd28e9c6896a)

**Comment by plateaukao** [comment]
On my devices, it seems I can't scroll with touch area on feedly.com. As you said, it may have different iframe or something that interferes the behavior. Glad that you find a way to make it work. :)

**Comment by bubbleguuum** [comment]
Yup it is caused because of frame focus and I also observed it on another web page. Focusing the frame clicking one of its element (if possible) fixes it. Maybe einkbro could focus the larger frame by default ?

**Comment by plateaukao** [comment]
by default, Einkbro does not inject any javascript codes to web content, so there's no way to do so. Also, I'm more a android guy, not web guy, so I don't know how to wrtie proper javascript codes for it. If you know how to do so, welcome to send a PR, I may try to integrate it as an option.

**Comment by bubbleguuum** [comment]
I realized that a single tap anywhere in the background of the frame (that is not a link) give it the focus, making this issue trivial to address by the user and I feel a bit dumb for not understanding that before submitting this issue.

**Comment by plateaukao** [comment]
It's great that you find an easier to way to make it work. :D
