### ISSUE TITLE
Tap tab or title for URL input

### ISSUE THREAD

**Issue by lawson85** [plateaukao/einkbro#273]
I think the only thing keeping this browser from default is the fact that I cat click the title or tab to get to URL input, I have to reach round for the button that usually isn't on screen.

**Comment by plateaukao** [comment]
what device are you using?
usually a 6" device could show the title button without problems.
If you are using devices less than 6", you can configure toolbar to show the pen button instead. It will open input field directly with less space on toolbar.

**Comment by lawson85** [comment]
Android 12. There are two titles, because I have tab bar enabled. The title that isn't in tab bar is pushed to the far left by other buttons I don't need to use such as the additional + button and the number of tabs

**Comment by plateaukao** [comment]
As I said, you could configure toolbar (available in menu) to hide title and + button, tab count button, and put on a pen button; so that the toolbar would be more appealing for your use.
