### ISSUE TITLE
infinite loop verfication_ gitlab.com

### ISSUE THREAD

**Issue by ghost** [plateaukao/einkbro#278]
* samsung internet_ 21.0, jquarks viewer_ 1.10.19: successful login
* 10.11.0 fdroid_ infinite loop verfication, unable to login_ gitlab.com
* os: android 9

**Comment by plateaukao** [comment]
If it’s related to cloudfare verification, you could try to replace the user agent as this release suggests.

https://github.com/plateaukao/einkbro/releases/tag/v9.22.0

**Comment by plateaukao** [comment]
Too bad to see that. It's more related to how cloudflare detect seem-no-so-official browser, instead of a direct issue inside einkbro. I couldnt do much now. 

Have you tried update System Webview on your device? It might help.
