### ISSUE TITLE
[tab bar] Move to next tab (to the right) at tab close.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#282]
First of all thank you for "tab bar" functionality, i've just discovered it and it's super handy!

One issue i have is that when i close current tab it moves to previous tab instead of moving to next, example

-, active tab is "website B"
[websiteA] [websiteB X] [websiteC] [websiteD] [websiteE]
-, if close it, it moves to the previous tab
[websiteA X] [websiteC] [websiteD] [websiteE]

In my opinion it's not UX friendly because
-, most people move from left to right when moving from tab to tab
-, it's in UX conflict with "new tab (background)". I mean say i am at tab 2, and i "new tab (background)"ed 10 links, now if i move to first of them (tab 3), read it, then close it i am not moving to next link, instead i am again moving to previous tab (on which i already was), of course i could scroll to very end (to tab 12) and read tabs backwords but imho it's not logical (unless you arabic :))

----
Update: I think i understand why you made tab close move to previous tab, cause on tab view (expanded tab widget) we usully move from bottom to top (cause bottom is nearest to our fingers). But since enabling tab bar i hardly ever use tab view.

Maybe it's good idea to add possibility to set in setting > behavior to move either to previous or to next on tab close? (so user can decide for himself what's most convenient for him)

**Comment by plateaukao** [comment]
* on tablets, tab bar is more useful than the vertical tab list. That's why I added the feature and use it all the time (and remove tab count icon from my toolbar). 
* I will consider adding option to move forward (instead of backward), when closing current tab.

**Comment by plateaukao** [comment]
https://github.com/plateaukao/einkbro/commit/de8e416af019f20c92c41b5aeb09a10e9e77b1fe

**Comment by gety9** [comment]
@plateaukao 

thanks for listening to feedback & constantly improving Eink Bro - it's amazing browser! with amazing maintainer :)

closing
