### ISSUE TITLE
save a new web to exist epub file can't insert a new charpter

### ISSUE THREAD

**Issue by myf9832** [plateaukao/einkbro#285]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: myfkindle-k4的Redmi Note 9 4G
 - OS: android 11
 - EinkBro Version 10.12.0

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

1. Click save epub
2. Click exist eoub file
3. book name keep default,charpter name is not exist
4. click ok ,then open this epub file

**Expected behavior**
had saved the chartper as step 3 and include saved  yesterday.
![Screenshot_2023-08-29-12-39-33-831_info plateaukao einkbro](https://github.com/plateaukao/einkbro/assets/46832911/b1d47084-47c3-4608-a8a0-c3afbaf54354)
![Screenshot_2023-08-29-12-39-21-859_info plateaukao einkbro](https://github.com/plateaukao/einkbro/assets/46832911/e496e1f9-723b-42e6-baf0-60177dcafb69)
![Screenshot_2023-08-29-12-36-37-338_info plateaukao einkbro](https://github.com/plateaukao/einkbro/assets/46832911/5106293b-a18d-487c-a30d-3d02b3a5eee4)
![Screenshot_2023-08-29-12-36-33-597_info plateaukao einkbro](https://github.com/plateaukao/einkbro/assets/46832911/f79ad04c-1d35-47a3-80b2-f371a3235075)

**Screenshots**

**Additional context**

**Comment by plateaukao** [comment]
@myf9832 
If you try to save to existing epub file, it should not show the dialog of asking for Book name. It looks like it can't open existing epub on your device. Could yous select the first item, to choose the eixsting epub file from system file picker again? It should work in this way (instead of choosing the epub file on the pop up list).

**Comment by myf9832** [comment]
i try save the epub file to sd storage, this issue can be closed .
