### ISSUE TITLE
When inputting into the lower half of the input box in the browser, the keyboard will block the interface.

### ISSUE THREAD

**Issue by WeihuaGu** [plateaukao/einkbro#289]
**What device and app version are you using**
 - Device: boox 
 - OS: android 10
 - EinkBro Version v10.13.1

**Describe the bug**
When inputting into the lower half of the input box in the browser, the keyboard will block the interface.

**Comment by plateaukao** [comment]
@WeihuaGu
Did you turn on "hide statusbar" feature in Settings> UI?
If so, you could turn it off. Now it's the reason why keyboard blocks the UI.
I am not sure why yet.

**Comment by WeihuaGu** [comment]
After turning off this option, it is indeed normal.
