### ISSUE TITLE
app crash when Saving epub 

### ISSUE THREAD

**Issue by myf9832** [plateaukao/einkbro#291]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: Sprd SC801a 
 - OS: Android 8.1.0, API 27
 - EinkBro Version 10.14.0  

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

Example description:
1. click 'save epub'
2. Click 'new Epub or from picker'

**Expected behavior**
can create a new epub file

**Screenshots**

**Additional context**
![crash1](https://github.com/plateaukao/einkbro/assets/46832911/cb62fffd-c2cb-41a9-b42c-d40575a34c0d)
![crash2](https://github.com/plateaukao/einkbro/assets/46832911/b00aaf08-fc4f-4488-b459-d9e476e60c9d)

**Comment by plateaukao** [comment]
It looks like 口袋閱 does not have file manager that supports SAF (Storage Access Framework). I will consider using other ways to support it in the future.
