### ISSUE TITLE
Google authentication being rejected

### ISSUE THREAD

**Issue by Norgus** [plateaukao/einkbro#295]
I attempted to log into chatgpt using my google account, and upon confirming my google login stuff with google, I got the following error page

```
You can’t sign in from this screen because this app doesn’t comply with Google’s secure browsers policy. If this app has a website, you can open a web browser and try signing in from there.

You can let the app developer know that this app doesn’t comply with Google’s secure browsers policy. Learn more about this error
If you are a developer of openai.com, see error details.
Error 403: disallowed_useragent
```

I thought I'd logged into Google services using eink bro in the past, so perhaps this is a recent ban / user agent snub?

**Comment by plateaukao** [comment]
@Norgus 
It's been fixed. You could try the nightly version on Readme, or wait for next version.
