### ISSUE TITLE
Page Reserved Height has no effect

### ISSUE THREAD

**Issue by mhantsch** [plateaukao/einkbro#303]
**What device and app version are you using**
 - Device: Onyx Boox Nova Air 2
 - OS: Android 11
 - EinkBro Version 10.16.1

**Describe the bug**
I set the Page Reserved Height to different valus, e.g. 50% but a page turn still moves by exactly the same amount. It seems the setting has no effect.

I am trying to get more of an overlap between pages but can't make it work. it does not matter if I turn pages using the device buttons or the on-screen page turn touch zones.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open web page
2. Go to settings and set page Reserved Height to 50%
3. Exit settings and page turn
4. The Page turns but only 1 or 2 lines of text remain visible from the previous page.

**Expected behavior**
Half of the text of the previous page should still be visible.

**Comment by plateaukao** [comment]
please only input digits. 
% is not allowed.

**Comment by mhantsch** [comment]
I did not put the % sign in the field, only the digits 50.

**Comment by mhantsch** [comment]
@plateaukao 
I did not realise this value was in pixels! Of course the feature works, now I have put in 250, and that makes a big difference. Maybe the text around the entry field should say "in pixels".

**Comment by plateaukao** [comment]
Yes, you are right. I'll add description to explain it's in pixels; and modify codes so that  users should explicitly add %, and  it will take the string as percentage.
