### ISSUE TITLE
Versioning issue Google Play (11.1.0) vs. latest Github release (11.0.0) - link to nightly build missing in Readme.md

### ISSUE THREAD

**Issue by g-roi** [plateaukao/einkbro#311]
There is a currently versioning discrepancy between Google Play (shows version 11.1.0) and the latest Github release (shows 11.0.0).

This results in an error when Google tries to update Einkbro when the Github version is installed.

I fixed it by installing the nightly build which is currently 11.1.0. But I realised that the link to the nightly build does not show up in the README.md file of Einkbro. I had to search for it.

Maybe it would be a good idea to add the link to the nightly build to the README.md file.
https://nightly.link/plateaukao/einkbro/workflows/buid-app-workflow.yaml/main/app-release.apk.zip

Thanks!

**Comment by plateaukao** [comment]
The reason why you cannot install in the Google Play store is because the signing key is different. Now that since you have installed the version from GitHub, you can go to settings > about eibkro and then you can find a button to update directly from there.

**Comment by plateaukao** [comment]
And, the link do show up in readme. It's a button next to Google play store icon

**Comment by g-roi** [comment]
> Now that since you have installed the version from GitHub, you can go to settings > about eibkro and then you can find a button to update directly from there.
Thanks, that is what I am doing. But since the version 11.0.0 Google Play Store thinks that Einkbro on Google Play is newer and always wants to install the Google Play version over the Github version. This of course fails every time because of the different signing keys and results in an Google Play Store error message.

> And, the link do show up in readme. It's a button next to Google play store icon
Thanks again, now I know that the "Snapshot" is the nightly build.

**Comment by plateaukao** [comment]
Next time I'll make sure the version on Google play store is not larger than developing version. 😄

**Comment by plateaukao** [comment]
@g-roi 
EinkBro app is suspended by Google Play Store, so this issue is no longer valide.

**Comment by uqs** [comment]
What happened to Play store? Due to device policies, I cannot sideload Apks on my main device.

Can we get it back in the store?

**Comment by plateaukao** [comment]
it's removed by google, due to policy violation. I added two buttons in settings  to allow users upgrade from github.
To be able to be listed in google play store again as a total new app with a different app name, I have to remove the button, and re-apply a new app all over  again.
I don't wanna waste my time doing so.

If you really need to have a install version on play store, you could try to release on google play store.
