### ISSUE TITLE
Some websites refuse to open or return an error.

### ISSUE THREAD

**Issue by Kasenkow** [plateaukao/einkbro#312]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: ONYX BOOX KON-TIKI 2
 - OS: Android 10
 - EinkBro Version 11.1.0

**Describe the bug**
Some working websites cannot be open on my device. They either return a message of error, or a blank page. Turning off AdBlocker did not help.

**To Reproduce**
Steps to reproduce the behavior.

Example description:
1. Go to https://www.dw.com/
2. See blank page

**Expected behavior**
A working web page (similar to mobile/desktop version).

**Screenshots**

**Additional context**

**Comment by plateaukao** [comment]
@Kasenkow I tried and it works. Could you try again?

**Comment by Kasenkow** [comment]
@plateaukao thank you very much for trying. No, on my side the issue still persists. Perhaps, there is something wrong with my e-book then. Before we close the issue, is there a way to extract logs?

**Comment by plateaukao** [comment]
@Kasenkow 
No, there's no logs for released version. Could list more websites that do not work well on your device? That may help me to investigate more.

**Comment by Kasenkow** [comment]
@plateaukao much appreciated. Another example would be me https://meduza.io/. This has slightly differenet behavior - it loads at first, but then throws an error without any paritular code or a message that could help figuring out what was the reason. There were other examples of such websites, but I cannot recall them at the moment. Yet another group of websites has other functionality issues, but I will omit mentioning this group here, to keep the issue track clean.

**Comment by wra1w0** [comment]
Maybe it has something to do with [this issue](https://github.com/plateaukao/einkbro/issues/304#issuecomment-1875317558). On some pages, I encountered similar behavior - no error message and the page does not load (Onyx Boox Page Android 11). Try switching the SSL Error dialog in Settings > Behavior > Show SSL error dialog. If it helps, then this is related to that dialog.

**Comment by plateaukao** [comment]
@wra1w0 
If you  mean some pages in google search results, that may be they are ads from Google. You could click links that are not makred as promoted by Google.

I'll try to fix this some day in the future.

**Comment by Kasenkow** [comment]
> Maybe it has something to do with [this issue](https://github.com/plateaukao/einkbro/issues/304#issuecomment-1875317558). On some pages, I encountered similar behavior - no error message and the page does not load (Onyx Boox Page Android 11). Try switching the SSL Error dialog in Settings > Behavior > Show SSL error dialog. If it helps, then this is related to that dialog.

Thanks for suggestion, @wra1w0 . Tried it, didn't work for me.

**Comment by Kasenkow** [comment]
@gety9 Germany. Tried VPN as well.

**Comment by plateaukao** [comment]
@Kasenkow 
I can kind of reproducing this issue on my hisense A5 device. However, it seems www.dw.com issue. I don't know what I can do from EinkBro side. Sometimes it may be due to old WebView version. You could try to update System WebView in your  BOOX device Google Play Store and see if it helps.

<img width="1423" alt="image" src="https://github.com/plateaukao/einkbro/assets/4084738/4d8a8ede-1d06-493f-98a9-1a2661c61100">

**Comment by Kasenkow** [comment]
@plateaukao 
I have updated the webview, it didn't work. But I think I know what's is common in all the cases: **those websites are live updates news**. I see the same at certain parts of CNN. For example this page doesn't work for me [CNN](https://edition.cnn.com/middleeast/live-news/israel-hamas-war-gaza-news-01-16-24/index.html) while the rest is perfectly readable. Or [Al-Jazeera](https://www.aljazeera.com/)
I installed Edge, Opera and Firefox for comparison. All of the browsers are opening all of the websites I mentioned in this issue. So it appears to be a bug after all.

**Comment by plateaukao** [comment]
too bad that I cant reproduce the issue now, and dont know whats the possible root cause of this issue.

**Comment by dredmorbius** [comment]
@Kasenkow FWIW both DW and Meduza **DO** work for me, v11.3.1

My suggestions were going to be other browsers, and possibly trying from another network, but it seems you've covered all those angles.

Another thought is to try a fresh EinkBro install or clearing all settings (perhaps best done on a separate account), and seeing if perhaps one of your settings might be triggering this.  I've run into another issue that seems to have had that as a factor in the past day or so.

**Comment by stacsk** [comment]
Google Play Store links don't open. I'm trying to view app pages in the browser. play.google.com opens but pressing on an app returns _net::ERR_UNKNOWN_URL_SCHEME_

For Brawl Stars, for instance, this is the URL EinkBro gets and fails:

intent://play.google.com/store/apps/details?id=com.supercell.brawlstars&pcampaignid=web_auto_redirect&web_logged_in=0&redirect_entry_point=hp#Intent;scheme=https;action=android.intent.action.VIEW;package=com.android.vending;end

This is the one Waterfox gets succeeds:

https://play.google.com/store/apps/details?id=com.supercell.brawlstars
