### ISSUE TITLE
EinkBro suddenly using a horrendously increased amount of mobile data on my phone

### ISSUE THREAD

**Issue by CottonEvoker** [plateaukao/einkbro#315]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Device: OnePlus Nord 2T 5G
 - OS: OxygenOS 13.0, Android version 13
 - EinkBro Version: v11.1.0 (12171640) 
 - 
**Describe the bug**
Since around Dec 19th, EinkBro on my phone has started using collossal quantities of my phon'es mobile data allowance, hundreds of times the amount it had been using daily, to the point where I have had to block its access to mobile data..

**To Reproduce**
No reproduction steps: Simply unexplained massive increase of usage by EinkBro of my data, even when I'm not using it. 

**Expected behavior**
Again unexpected and highly unwanted massive usage of my mobile data. 

**Screenshots**
I am supplying various relevant screenshots, and I refer to these below in "Additional context".

**Additional context**

- Per my comments on a separate issue thread I opened ("Issue with sharing to EinkBro from "Palabre" Android application #300"), I have been very impressed by EinkBro since starting using it three or four months ago.
- Up until December 24th I was enthusiastically using it across various Android devices, in anticipation of (at some point) using it on a future Android-powered eink ereader device.
- I got a terrible shock though on Christmas Eve morning (December 24th), when I realised that for about the previous week, EinkBro had been using up absolutely obscene quantities of my phone's mobile data allowance (6gb of mobile data on December 24th alone) for a reason I don't understand and am unable to get to the bottom of.
- I discovered that morning (i.e. Dec 24th) that, of a 20gb mobile data bundle (that renews every 28 days and that I'd renewed just a day or two prior [i.e. on December 22nd or 23rd]), only 11.3gb was left: Almost 9gb of data unexpectedly gone in just under 2 days, during which time I had barely even used my phone. To the best of my knowledge too, I'd barely used any mobile data at all on my phone over the previous week.
- I have a data usage monitoring app called "Glasswire" on my devices including my phone.
- On checking data usage in Glasswire on my phone, I discovered EinkBro had used 6.43gb a data on December 24th alone. 
- Of course, I had to immediately block EinkBro in its Android app info setting from using any further mobile data. 
- On then reviewing EinkBro's data usage history in Glasswire, it's clear something started going wrong around Tuesday, December 19th, when EinkBro shows as having used over 3.82gb of data.  
- As for EinkBro’s usage of Wifi data, it had also started using a massively disproportionate amount of this too, again since around December 19th.

I don’t wish to overload this issue report with too much detail, and I can and will supply any additional information you need to enable you diagnose the issue, or to get to the bottom of it. Please just let me know any information you’d like or need me to provide.

What I do want to provide here though are are selections of screenshots I took from Glasswire on my phone that illustrate the drastic increase in mobile data usage by EinkBro since December 19th. Up until then, EinkBro (on those days when I used it) would never show as using more than around 20mb of mobile data.

I supply four PDFs, one each showing mobile & Wifi data usage for the period Dec 17th to 24th, and one each too showing mobile & WIfi data usage for the months October – December.

"Phone data usage (mobile), Dec 17 – 24.pdf"
* On this you can see how mobile data usage by EinkBro slyrocketed over the 8-day period.

"Phone data usage (Wifi), Dec 17 – 24.pdf"
* Over the same 8-day period, wifi data usage by by EinkBro can also be seen to increase dramatically.

"Phone data usage (mobile), Oct – Dec.pdf"
* The notable items in this three-month comparison are, in my view, as follows:
- In October, EinkBro’s total mobile data usage for the month came in at just 40mb, meaning it does’t even show on the screenshot because it doesn't rank high enough. 
- The screenshot for November reflects (correctly) that I’m starting to use EinkBro a lot more by Novmber, with total EinkBro mobile data usage being 654mb for the month: This likely aligns very correctly with my actual usage.
- An additional screenschot (just FYI) shows a ‘spike’ date of Nov 19th, when (on a single day) my phone "Tethering"'s usage of mobile data is disproportionately high at 14.8gb. Again, this is just a side FYI, nothing to do with EinkBro.
- Finally, December: Here we see that EinkBro has gone 'out of control', crashing up through 15.5gb of mobile data usage.

"Phone data usage (WiFi), Oct – Dec.pdf"
* On these screenshots, we can again see the marked increase over the three months in EinkBro's Wifi usage too:
- EinkBro's Wifi data usage in October was just 30mb, i.e. wasn't high enough to rank and show on the screenshot.
- A lot higher in November at 1.87gb for the month, but still nothing too worrying.
- Becoming very problematic then in December, at 4.9gb for the whole month.

I do hope this can be resolved because, as you will understand, I have had to stop using EinkBro for the time being, until I can be confident this unexpected demolishing by it of my mobile data won’t happen again.

Two final thoughts/questions:

1) Is there a possible link with the EinkBro update released on Dec 17th, a release that introduced support for Article Read with Voice by Open AI tts API?
2) If you think it might allow me to revert my EinkBro usage to the experience I was having with it prior to December 19th, I’m open to downgrading to a previous release. Is downgrading to the previous version an option when I’m using the Play Store version of EinkBro? 

Thank you in advance for any time you take to look into / investigate this.

--- 

[Phone data usage (mobile), Dec 17 – 24.pdf](https://github.com/plateaukao/einkbro/files/13806064/Phone.data.usage.mobile.Dec.17.24.pdf)
[Phone data usage (Wifi), Dec 17 – 24.pdf](https://github.com/plateaukao/einkbro/files/13806065/Phone.data.usage.Wifi.Dec.17.24.pdf)
[Phone data usage (mobile), Oct – Dec.pdf](https://github.com/plateaukao/einkbro/files/13806066/Phone.data.usage.mobile.Oct.Dec.pdf)
[Phone data usage (WiFi), Oct – Dec.pdf](https://github.com/plateaukao/einkbro/files/13806067/Phone.data.usage.WiFi.Oct.Dec.pdf)

**Comment by plateaukao** [comment]
hi, providing yhe pdf does not help because I can't tell what sites you are loading, how many tabs ypu oepned when you use EinkBro. You could try to disable load other tabs in background in settings. also, you could long press setting button, and toggle off background playing to see if it helps.

**Comment by plateaukao** [comment]
1. all releases are here. https://github.com/plateaukao/einkbro/releases
 but they are not compatible with versions on google play store.
2. with google play version, no, you cant downgrade. 
You can uninstall it and install versions  from github releases.

**Comment by CottonEvoker** [comment]
Thank you for the quick reply.

The screenshots were only to show the data usage extent.

"I can't tell what sites you are loading"

Okay, so I can see that one particular site/page (at www.nbcnews.com) was definitely to blame: It contains a video (auto-playing probably at high res) that was wolfing down my data. (The fact it may have been playing "muted" probably added to the problem too, as I may not even have heard it playing).

Disabling "Loading non-active tabs" helps: Video stops on switching tab.

Also: I have the "Keep Screen Awake" setting enabled, so that I think what may have happened on December 24th is I dropped off (to sleep) in the early hours with the nbcnews.com webpage open, and video continued auto-playing through the night. (In fact I think I remember the battery being empty when I woke up the next morning, and now I think I know why).

"Background Play" (long press menu/settings button) was already disabled (unticked).

Websites forcing video to play unwantedly is a scourge that afflicts the Internet generally and that EinkBro probably can't do a great deal about, any more than any other browser.

I don't think downgrading is necessary then.

I'll start using EinkBro again. I'll just need to watch out for those video auto-play websites.

Thank you again.

**Comment by CottonEvoker** [comment]
By the way, a suggestion: Would really like to see "Share Link" (under Share & Save) enabled as an option under "Toolbar setting", so it can be made a visible icon on all tabs.

**Comment by plateaukao** [comment]
Got it. I'll added to toolbar icons configuration in following releases, so that you can added to toolbar. 😃

**Comment by CottonEvoker** [comment]
Super, thanks so much.

**Comment by dredmorbius** [comment]
@CottonEvoker Mal-behaved webpages with auto-playing media have been hammering data quotas for decades.  A hosting site I worked at got hit by this (interaction between the webpage and one specific Web browser) when I worked there in the early aughts.  Blew through our colo's 95%ile data rate...

@plateaukao The feature I'd like to see, if at all possible, is permitting video on a whitelist-only basis, and / or prohibiting video autoplay.  Since I'm on an e-ink device, video quality is _at best_ pretty poor, and since I'm usually using Einkbro at high display quality, autoplay video or animation just flickers the screen like mad.  Given the likelihood of blowing through data caps, as well as slow performance on low-quality links, this should be a general plus.

(If you'd prefer I made that request in a separate issue I can do so.)

**Comment by plateaukao** [comment]
@dredmorbius 
In odrder to know whether a web page has videos or not, I need to inject javascript codes into every web page to detect it. If so, then try to pause it or allow it to play. This is too intrusive, and I often use my EinkBro to watch videos; so I may not add the feature in the near future.

**Comment by dredmorbius** [comment]
@plateaukao Is there any way to simply (hah!) toggle support of well-known video codecs?

E.g., with option enabled, codecs will play.  Disabled, those specific codecs won't.

There's always the option of a site to implementing video or animation by other means (gifs, though that should also be toggleable), SVG, HTML5 Canvas, etc., and new codecs might appear from time to time.  But anything from a 75--90% solution would be very much appreciated.

My own preference is to play media in a third-party app.  Most often that's mpv in a Termux session (audio only).  Occasionally, VLC.  Putting media/video in the browser is popular but IMO a huge mistake.  Though I suspect it would be painful to try to stem that tide.

**Comment by plateaukao** [comment]
@dredmorbius 
As far as I know, no, there's no simple way or easy way to toggle video codecs. That's not how codecs work and it's buried deep in the browser engine or android system engine which I can't touch as an app dev. 
At most, it's only possible to inject javascript in all websites (in EinkBro), looking for video elements, and try to control it. However, that's not what I'm going to do any time soon. For these scenarios, please use other browsers that support the behavior your need.

**Comment by dredmorbius** [comment]
@plateaukao Understood and appreciated, thanks.

**Comment by CottonEvoker** [comment]
> Got it. I'll added to toolbar icons configuration in following releases, so that you can add the button to toolbar. 😃

Hi Daniel, 

I like the new toolbar configuration in 12.4.0.

On an issue/post I opened earlier this year (#315) I mentioned (as a side note) that it would be nice to be able to add the Share menu to the toolbar. You were going to look into adding it in a coming release. 

There've  subsequently been quite a few releases of EinkBro, but I still don't see the Share icon as an option.

If you find the time, can you please take another look at implementing this?

Thanks.

**Comment by plateaukao** [comment]
@CottonEvoker 
will do in near future. finally new toolbar configuration UI is done, so there's more room to show the icons to be added. :)

**Comment by plateaukao** [comment]
Voila !
https://github.com/plateaukao/einkbro/commit/583a1a06b722ee3f8f3697727445f8f798c22d19
<img width="357" alt="image" src="https://github.com/user-attachments/assets/472e8843-d535-4d01-ab60-1b1b15deacf9">

**Comment by CottonEvoker** [comment]
My goodness, EinkBro doesn't ever stop being great and getting better. Look forward to seeing it in next release. Thank you so much.
