### ISSUE TITLE
Saving epub on long page just sits there spinning

### ISSUE THREAD

**Issue by uqs** [plateaukao/einkbro#316]
**What device and app version are you using**
 - Device: Pixel 6
 - OS: stock Android 14
 - EinkBro Version: v11.1.0

**Describe the bug**
No epub is getting created, though it's a slightly bit non-deterministic

**To Reproduce**

1. Go to https://slatestarcodex.com/2014/07/30/meditations-on-moloch/
2. Save to Epub (either existing or new, doesn't matter)
3. The progress spinner comes up and stays forever, but nothing much else happens.
4. Tapping anywhere on the app just makes the progress spinner disappear.

**Expected behavior**
Many, many articles on that website do properly save as epub, so I suspect it has something to do with the length of that particular blog post.

Now, I did manage to actually save this article as a chapter on a different epub, once, but I can't reproduce it. While the spinner/progress is showing, I _think_ I hit the "reader mode" button and then after a while the "what app do you wan to open the epub with" dialog came up. But I can no longer get this to work at all :(

**Comment by plateaukao** [comment]
The page is too long and there are many images in it. It takes time to download all images. It should work if you're willing to wait long enough.

**Comment by plateaukao** [comment]
you could try to scroll to the bottom of the page, or switch to reader mode before saving it as epub. This might helps.

**Comment by uqs** [comment]
Thanks for the response!

* When you say "many images", do you mean the avatars of the people posting comments? None of these (comments) make it into the epub, so isn't that irrelevant?
* I now did wait patiently, and indeed, after 5 minutes it was finished with the epub. Is there a way to profile this operation? Usually pages half as long only take 5 seconds to get converted.
* Why does the progress spinner disappear if I tap anywhere? Does that abort the conversion or will it continue in the background?
* This luckily seems to also work when I just let the phone go to sleep, though it will then never pop up the "open epub in..." dialog, which is a bit strange and makes it look like the process aborted.

So how can the progress spinner be made to stick around to better indicate that things are still churning?

**Comment by plateaukao** [comment]
it's working in background, so hopefully it should continue making epub if you close the dialog.
currently there's no way to profile the behavior, because most of the websites either generate epub immediately, or just cannot work. 
For long page like this, I will check what happened when I can access my computer.
