### ISSUE TITLE
Saving webpage as epub always creating new epub file with size 0kb

### ISSUE THREAD

**Issue by amsitlab** [plateaukao/einkbro#317]
**What device and app version are you using**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android 9
 - EinkBro Version: 11.0.0

**Describe the bug**
When I saving webpage as epub, einkbro just creating new epub file with size 0kb without crash/error message, also no content when I open that file with einkbro.

**To Reproduce**
Steps to reproduce the behavior.

1. Go to webpage
2. Click on Menu
3. Click Save as epub
4. Reload page (**auto**)
5. Open file explore
6. Click epub file (**new epub file created by Einkbro**)
7. Open with Einkbro
8. Just blank page with einkbro menu (no content, no item list)

**Expected behavior**
Success to saving epub.

**Comment by dpicassom** [comment]
I'm having the same issue on Onyx Poke3.when using built-in file manager

when using 3rd party file manager, it just returns to the browser without doing a thing


 Any solutions yet?

**Comment by plateaukao** [comment]
@dpicassom 
what do you mean by using 3rd party file manager? for selecting a file?
could you check whether the website you want to save as epub, can enter reader mode successfully?
Some websites do not allow being saved as epub.
