### ISSUE TITLE
"Google in Place" translation mode doesn't work on some websites.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#318]
- Device: Boox Note Air 2
 - OS: Android 11
 - EinkBro Version 11.0.0

Translation feature is supper useful. "Google in Place" is most reliable/conveniet mode and it works on 90% of websites i try to translate. 

But it does not work on some pages, example:
https://www.reddit.com/r/brasil/comments/192uegx/galera_estranha_na_minha_rua/
https://www.zhihu.com/question/538919973

Steps:
1, open the link
2, press translate icon
3, nothing happens

I was thinking it's impossible to translate these types of pages "in place" (without using "whole page" loading). But Brave browser managed to make it work, screenshots:

Reddit:
![Screenshot_20240110-041446](https://github.com/plateaukao/einkbro/assets/16415882/e896acd7-44ce-4eca-adeb-1ce58373f542)

Zhihu:
![Screenshot_20240110-041543](https://github.com/plateaukao/einkbro/assets/16415882/b5adf6fc-d26b-4fde-8f1f-69ea37ca9cf6)

If you switch to "Google Whole page" then it works, but i find "Google Whole Page" mode much less convenient then "Google In Place" cause you can't translate several pages/tabs and switch between them (any time you translate next page/tab previous translation is lost)

**Comment by gety9** [comment]
@plateaukao thank you for explanation. So we are not able to fix it, right? (it's fine, not big deal). Then i will close the issue?

**Comment by plateaukao** [comment]
No, I don't know how to fix it. Leet me close this issue. :(
