### ISSUE TITLE
Text select paste new line bug.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#319]
**What device and app version are you using**
 - Device: Boox Note Air 2
 - OS: Android 11
 - EinkBro Version 11.0.0

**To Reproduce**
1, go to page with text (example https://www.reddit.com/r/Poetry/comments/192stl2/poem_my_papas_waltz_by_theodore_roethke/)
2, copy text containing lines
3, insert in comment section 

**Screenshots**
Eink Bro (has ';\n' instead of new lines)
![Screenshot_20240110-071204](https://github.com/plateaukao/einkbro/assets/16415882/a7ff2afd-bb54-4d45-ac48-9b71887340fc)
![Screenshot_20240110-071406](https://github.com/plateaukao/einkbro/assets/16415882/ffe5d431-529a-4771-bc07-38407adc0f88)

Chrome (works correctly)
![Screenshot_20240110-071105](https://github.com/plateaukao/einkbro/assets/16415882/c3b59094-9f07-4d05-bc43-f7ed5757472f)
![Screenshot_20240110-071427](https://github.com/plateaukao/einkbro/assets/16415882/cab2c9fd-ac28-4785-95c9-a24e650a4f4b)

**Comment by plateaukao** [comment]
will check if i can fix it.

**Comment by plateaukao** [comment]
fixed in 0cd63de
