### ISSUE TITLE
When downloading, auto populated file name is "default.aspx".

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#327]
**Env**
 - Device: Boox Note Air 2
 - OS: Android 11
 - EinkBro Version 11.0.0

**Bug**
On some websites when clicking download file default file name is "default.aspx" Instead of one that website suggests, say "mathpuzzles2024". And if you try to download then system can't open it (cause of this name)... 

**Steps**
1, Go to https://www.nasdaqomxnordic.com/aktier/microsite?Instrument=SSE249469
2, Click "Fact Sheet"
3, Try to save file

**Additional**
I saw it on many websites, but assumed it's problem of websites - developers are lazy to suggest human default name. But no, if i go to same website in Kiwi browser default name is human.

**Screenshots**
(first 2 from bottom are kiwi and chrome downloads, last one is eink bro)
![Screenshot_20240119-165000](https://github.com/plateaukao/einkbro/assets/16415882/cc9bccf0-5e26-46a0-b45b-4fa259efe637)
![Screenshot_2024-01-19_16-51-36](https://github.com/plateaukao/einkbro/assets/16415882/9f28aaa5-063a-49c9-a2bf-a1f96b17051a)

**Comment by plateaukao** [comment]
The download filename is too complicated to handle. From what EinkBro can get (from the website) in this case, it's default.aspx. You can save it as what_ever_name.pdf, and then you can open it correctly. Unless someone offer a more better way to handle filenames, I have no intentions or methods to fix this.

In this case, I suggest using other browsers to download files. That's what I usually do.

**Comment by plateaukao** [comment]
By the way, kiwi browser is almost identical as Chrome, they have the same core engine. However, EinkBro uses WebView; it's only a thin layer, so a lot of handlings need to be done by dev.

**Comment by gety9** [comment]
@plateaukao 

Thanks for explanation on Kiwi, Chrome, etc - i wasn't aware that those examples are useless to our (webview) case.

I understand that download filename process is complicated - it just it's so annoying to switch to other browser when i have everything in Eink Bro (all my bookmarks, all action icons in familiar places, etc) :).

If download in cases like these (deafult.aspx, google trasnalte web file, etc) works in other webview browser (say FOSS browser) - can we "take inspiration" from it? (so it easier/faster to implement and will be worth persuing?)

If not, i understand and will close all my download related issues and will ignore all download related bugs in future.

**Comment by plateaukao** [comment]
>If download in cases like these (deafult.aspx, google trasnalte web file, etc) works in other webview browser (say FOSS browser) - can we "take inspiration" from it? (so it easier/faster to implement and will be worth pursuing?)

Yes, it does help if you find it works in FOSS browser, since FOSS browser also uses WebView and it's Open Source. Is it true? if so, I could take a look at FOSS browser implementation, and see if I can port that implementation to EinkBro. If so, maybe I can even remove the file renaming step.   (I found it tedious but no way to bypass it now)

**Comment by plateaukao** [comment]
@gety9  please have a try with version 11.3.0
https://github.com/plateaukao/einkbro/releases/tag/v11.3.0

**Comment by gety9** [comment]
@plateaukao works great! thank you! closing!
