### ISSUE TITLE
Configure / tune Reader Mode margins, especially on larger devices

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/einkbro#33]
Using an Onyx BOOX 13.3" device, the margins in Reader Mode run uncomfortable close to the sides, top, and bottom of the display.  I'd much prefer more whitespace around the document text.  Mozilla Fennec Fox Reaer Mode and the Pocket reader (either Web client or Android app) both offer much wider side margins, about 30mm for Fennec Fox and about 15--20mm (varies by font size) in Pocket.

Text excessivly close to margins becomes difficult to read.

Either increasing defaults or offering a user control for this would be appreciated.

**Comment by plateaukao** [comment]
Hi, @dredmorbius 
I'll try to add an option in Settings to allow wider margins in case users are using larger eink devices.

**Comment by dredmorbius** [comment]
See also #34

**Comment by dredmorbius** [comment]
Updating `assets/readerview.css` to read:

```
.mozac-readerview-body {
  padding: 10px;
  background-color: #ffffff !important;
  color: #000000 !important;
  margin: 10%;
}
```

Where the additional property is a 10% margin, would address most of my concerns.

10px for a 13" 220 dpi device ... is vastly insufficient.

A 10% margin should scale proportionately for all devices.

**Comment by abstrickland** [comment]
This is still an issue that would be helpful to have changed. The ability to set a default margin would be very helpful for reading on large devices.

**Comment by plateaukao** [comment]
@dredmorbius 
`margin: 10%` is too much for most devices, since it means 10% on left, and 10 on right. 20% of the screen is not used.

@abstrickland 
The feature is added with latest commit. Will be released in next version.
<img width="473" alt="image" src="https://github.com/user-attachments/assets/889cd310-95c9-4ffc-ac97-72ebaa149292">
It's configurable next to page reserved height.

**Comment by dredmorbius** [comment]
@plateaukao Thanks so much, I've been waiting on this one for a long time.

I'd prefer margin as %age rather than pixels, though I can live with the latter.

**Comment by dredmorbius** [comment]
I just wanted to follow up, this change makes a _huge_ difference in readability for me, I really appreciate it.

I've settled on about 160 px padding, which is about 10% (2200 x 1650 px on my Onyx BOOX Max Lumi).  For some of us, margins make for readability.

**Comment by abstrickland** [comment]
I one hundred percent agree. This option makes a huge difference on a large screen.

**Comment by plateaukao** [comment]
I already forgot that I have implemented this feature. 😅
