### ISSUE TITLE
(UX) Change bookmark sorting from alphabet to position based.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#333]
Opening it as a bug cause we already have the bookmark feature, it's just that it have small UX flaw.

If you consider it to be a new feature please move to Discussions / Ideas.

------

**Env**
 - Device:  Boox Note Air 2
 - OS: Android 11
 - EinkBro Version: 11.3.1

**Description**
Bookmarks feature is amazing! Layout, sizes, number of bookmarks per folder - everything is perfect, but (in my opinion) there is one UX flaw - because bookmarks are sorted by alphabet any time you add new bookmark (earlier letters are the worst A... etc) they change position of all older bookmarks. So you have to relearn position again.

It's like if position of icons ("+" net tab, etc") would change from time to time - user won't be happy :)

If we add possibility to edit position of bookmarks (per folder) it will give us:
- 1, ability to preserve position / muscle memory
- 2, place most important bookmarks in most convenient / reachable location (closer to bottom , etc)

Possible implementation:
1, Each new bookmark is added on top of older ones (the last)
2, If user drags exisiting bookmark to new positon (if it's needed, before he must press icon to enter dragable mode) or deletes it - positons are reassigned (dragged bookmark gets new positon, say "14", all bookmarks above "+1" to it's position; in case of deletion positons of bookmarks above old one "-1" to it's position).

(to remember position we can store "position : number" for each bookmark)

**Comment by plateaukao** [comment]
I would love to have bookmark manual ordering too, but it takes more effort to implement(need to change database schema too), considering now it also supports folders. I usually manually add prefix number in bookmark name to kind of as a workaround. I’ll implement it when I found it intolerable.

**Comment by gety9** [comment]
@plateaukao sure, I understand. thank you for suggesting prefix number trick, I didn't realize I kind do it :) so it's sorting by bookmark name (and we can influence it), not by page url/title :)

**Comment by plateaukao** [comment]
@gety9 
Added bookmarks manual sorting in latest commit. 
You could try snapshot version to have a trial. (still a bit buggy, but works as expected. could be triggered in bottom of bookmarks dialog)

**Comment by plateaukao** [comment]
supported
