### ISSUE TITLE
When launching einkbro a new tab is always created.

### ISSUE THREAD

**Issue by AJolly** [plateaukao/einkbro#334]
When you run this directly from a launcher, it always creates a new tab rather than showing you the most recently used tab.  This is nonstandard  (and means you can't easily switch back to einkbro from a quicklauncher)

**Comment by AJolly** [comment]
(If it helps, I'm using eink bro with a boox page and want to add it to the navball quick launch, but right now it always opens a new tab.

**Comment by plateaukao** [comment]
navball quick launch is not a normal launcher. If you can launch einkbro in BOOX page home screen from background without creating new tab, and it only happens when using navball; then it must be **navball** doing something different. I don't know what it did to cause this issue.

**Comment by AJolly** [comment]
I ran some tests -  I think it's the behavior of the intent android.intent.action.VIEW.

If you call Chrome with that intent for example, it shows your last open tab.

(Tested using shortcut maker)

If you do it w/einkbro it force opens a new page.

I appreciate this app by the way, you like how I can automatically force a white background.

**Comment by plateaukao** [comment]
> I ran some tests - I think it's the behavior of the intent android.intent.action.VIEW.
> 
> If you call Chrome with that intent for example, it shows your last open tab.
> 
> (Tested using shortcut maker)
> 
> If you do it w/einkbro it force opens a new page.
> 
> I appreciate this app by the way, you like how I can automatically force a white background.

thanks for the debugging. I changed the behavior when there's no url attached with action_view. hopefully it's fixed in snapshot version.
