### ISSUE TITLE
Switching up/down direction for touch pagination changes button speed

### ISSUE THREAD

**Issue by AJolly** [plateaukao/einkbro#338]
11.3.1

Weird little bug, by default the touch pagination buttons respond instantly and you can hold it down and it will rapidly scroll to the top or bottom of a page. If you switch the direction, they respond significantly slower (repeat threshold/speed)?

Tested this a few times.

(Ps. Related feature request: I love if we could somehow tie the up down directions to the device rotation, Ie portrait versus inverted portrait.

(A lot of ebook readers only have physical buttons on one side of the device, id like to be able to always have the down action be on the side farthest away from the buttons. )

Or if there's a way for me to set the setting via tasker I can diy.)

**Comment by plateaukao** [comment]
sorry, I dont't understand your related feature request.
as for long press luggish, I'll check why.

**Comment by AJolly** [comment]
> sorry, I don't understand your related feature request. 

Does this make more sense?  Trying to make it easier for one hand operation.  
So either 
1) tie the touch pagination buttons to the device rotation.
2) let it be a setting that's controllable by an external script or plug in like Tasker.
3) add a option that combines the current left + right options
4) let the middle/bottom/two sides options work as down arrows on both sides

![IMG20240215101702~2](https://github.com/plateaukao/einkbro/assets/91493/656e9398-fba0-4230-b59b-6d55a638c71b)

![IMG20240215101638~2](https://github.com/plateaukao/einkbro/assets/91493/ff759881-3e68-48f3-b81d-dfc7618e3df9)


Minor bug: the labels for middle and bottom are flipped:
 
![IMG20240215101532~2](https://github.com/plateaukao/einkbro/assets/91493/06945266-fd9d-4fd7-a826-64dda403404c)
![IMG20240215101539~2](https://github.com/plateaukao/einkbro/assets/91493/36e862e9-dac8-4edc-b30c-d176afc5b191)

**Comment by plateaukao** [comment]
for screen rotation, please configure toolbar to add the rotate button directly. (it's available in action menu)
it's not so intuitive to rotate device by touching screen area. 
as for script or plugin to control behavior, sounds like  a good idea, but I have no time to implement so. Thanks for the siggestion. If you can send a pull request, I would love to revoew it.
