### ISSUE TITLE
Reading mode format

### ISSUE THREAD

**Issue by Bearnagh** [plateaukao/einkbro#34]
Hello
Any plans to enable settings for formatting the Reading mode? 
For example the font type and size. 
I would like to default to a Sans Font, Bold and define a different font size than in the main browser for a consistent experience.

Thanks

**Comment by plateaukao** [comment]
Now the reader mode and normal web browsing using the same configurations. It would take some effort to separate the configurations. I'll put this feature into future TODO items. Thanks for the suggestion.

**Comment by dredmorbius** [comment]
See also #33

**Comment by plateaukao** [comment]
supported
