### ISSUE TITLE
(UX) Open in background and hh for history widget.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#342]
Currently history widget allows to open only 1 page at a time, it works well if user (from title and Month day) was able to correctly guess what page he was looking for. From my experience however usually you don't know 100%.

Example:
I needed to revisit stackoverflow page on \K regex, "\K regex" brought nothing, so searched "regex", i remember vaguely day and time... But still i need to open 3-4 pages at least :)
![Screenshot_20240219-101523](https://github.com/plateaukao/einkbro/assets/16415882/c545f4de-5228-42d4-b361-af990d651bf4)

Now to do that i will have to:
1, open page 1
2, press "+" / new page
3, "regex" in imput filed
4, scroll up
5, open page 2
6, repeat [2-5] * of times i guess wrong :)

How about we improve it a little?
-, allow to open in background, either with long press and pop up widget, or maybe better same as in bookmarks (if you press on page icon it opens in background if you press in middle it opens in foreground)
-, add hhmm to visit, or at least hh. Cause just Feb 16 is not enough.
Feb 16, 2pm; Feb 16, 3pm; Feb 16, 4pm
Or similar will be better.

**Comment by plateaukao** [comment]
Hi, @gety9 
I don't use history that much, so won't spend time on enhancing it.
If you send a pull request, I can review if the codes fit in.

**Comment by plateaukao** [comment]
for more advanced usage, please send the PR, and I will review. :)
