### ISSUE TITLE
I can't install einkbro builds from github. It can only be used from f-droid.

### ISSUE THREAD

**Issue by Josegithub2023** [plateaukao/einkbro#350]
When I want to install, I enable installations of unknown applications, when the installation finishes it says: The app was not installed.
But it can be installed from f-droid although the latest version is not available as github
My device si a Lenovo Smart paper.

**Comment by Josegithub2023** [comment]
Help me please!

**Comment by plateaukao** [comment]
it looks like you already installed some version that is compatible with fdroid one, so now you can only upgrade from fdroid. If you want to use gihub version, you jave to uninstall your current version, and have fresh install from github.

**Comment by Josegithub2023** [comment]
I managed to install other versions of eink bro using f-droid. but they still have the fundamental problem that I wrote in the following post, if you can help me it would be great, https://github.com/plateaukao/einkbro/issues/351#issue-2159611192

**Comment by Josegithub2023** [comment]
Help me please!

**Comment by plateaukao** [comment]
since you could install versions from fdroid, I'll close this issue.
