### ISSUE TITLE
Page scroll is broken in v11.4.0

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/einkbro#358]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**
 - Onyx BOOX Max Lumi: 
 - OS: Android 10
 - EinkBro Version 11.4.0

**Describe the bug**
When manually scrolling within a Web page, page jumps back and forth ~25% of screen.

**To Reproduce**

Example description:
1. Go to an arbitrary web page, e.g., <http://68k.news>
2. Scroll page down by dragging finger or stylus along screen.
3. Displayed page jumps up/down after removing finger or stylus from screen.

**Expected behavior**
Page should scroll while touch is actively engaged, and remain in the last position after finger or stylus is removed.

Note that the toolbar also appears _while scrolling down_, rather than only in scrolling _up_, despite having selected "Hide toolbar" under the "Toolbar" settings menu.

**Screenshots**

**Additional context**
I've reverted to and frozen at v11.2.0 which resolves this and other recent Einkbro changes.

**Comment by plateaukao** [comment]
will look into it.

**Comment by ziggyb1013** [comment]
I'm seeing this issue too as I was just going to file the same issue but with a Boox Note Air (FW 2023-12-12_21-24). But for me it happens more then you pinch and zoom. It jumps around A LOT.

I was using v11.3.1 and it didn't happen. When I updated to to 11.6.0 it started happening. 

I've attached video.

https://github.com/plateaukao/einkbro/assets/111400148/33fbb955-7e85-4d42-8886-9cc7a04f7b4e
https://github.com/plateaukao/einkbro/assets/111400148/905be2fc-4562-409f-b429-300e0c0debb4

**Comment by plateaukao** [comment]
@ziggyb1013 
Do you also turn on "hide toolbar" option?
I had a quick fix in snapshot version.
If you install einkbro from github, you can install it and check if it fixes the problem.

**Comment by ziggyb1013** [comment]
Yes, I have "hide toolbar" when scrolling enabled.

I can try it out, but where can I get the snapshot version?

**Comment by plateaukao** [comment]
you can go to settings and click on about einkbro. and choose, update woth snapshot. If your einkbro is not originally installed from github, then it's not working, you have to wait for fdroid's release.

**Comment by ziggyb1013** [comment]
I updated via snapshot to 11.6.1 (03251352) and the scrolling and zooming seems to be fixed!
