### ISSUE TITLE
Version v11.6.0 breaks setting einkbro as a default browser

### ISSUE THREAD

**Issue by mcrosson** [plateaukao/einkbro#359]
**What device and app version are you using**
 - Device: boox palma and samsung z fold 4
 - OS: android 11 and android 14
 - EinkBro Version: v11.6.0

**Describe the bug**
When upgrading from v11.5.0 to v11.6.0 I can no longer set einkbro as the default browser and when I click a link in another app, einkbro is not shown as a valid browser for opening a standard https url

**To Reproduce**
1. Install v11.6.0
2. Click a link in FeedMe, Wallabag, other apps that open urls, einkbro will not be an option for opening the url in the list of apps shown
3. Open settings then default apps and then try to set einkbro as the default browser, it will not be present

**Expected behavior**
Previously opening links and setting einkbro as the default browser worked.

**Additional context**
I've tried both the f-droid and github releases of v11.6.0 and both have the problem described above

**Comment by plateaukao** [comment]
thanks for reporting this issue. I'll check if I can reproduce it.

**Comment by plateaukao** [comment]
fixed in 11.6.1

**Comment by mcrosson** [comment]
Thank you for sorting this so quickly. I really appreciate it.  👍
