### ISSUE TITLE
Crash when opening a local html file

### ISSUE THREAD

**Issue by chwt163** [plateaukao/einkbro#364]
Einkbro crashes immediately after launching, and in a flash

**Comment by chwt163** [comment]
[index.html.zip](https://github.com/plateaukao/einkbro/files/15198323/index.html.zip)

**Comment by plateaukao** [comment]
@chwt163 please follow issue template to provide necessary information.

**Comment by chwt163** [comment]
- Device: HONOR BKL-AL20
 - OS: Android 10 API29
 - WebView: 118.0.5993.80
 - EinkBro: V11.6.1
 
To Reproduce:
Click on an HTML file in the file manager and select to open it with Einkbro, Einkbro fails to start

**Comment by chwt163** [comment]
Just found out, open Einkbro first, and then choose to open the html file with Einkbro in the file manager, Einkbro will not crash.
 If it's a cold start, it crashes.
