### ISSUE TITLE
PageDown/PageUp function not working on certain website

### ISSUE THREAD

**Issue by xqdd** [plateaukao/einkbro#366]
example1：https://wangwei1237.github.io/monolith-to-microservices/docs/What_Are_Microservices.html
example2：https://www.xiaolincoding.com/network/1_base/tcp_ip_model.html

Neither the touch area nor the volume button work, but when I connect a physical keyboard and press PageDown/PageUp/Space key,  it working

**Comment by xqdd** [comment]
The weird thing is that it works fine on my phone, but not working on my E-ink device(IReader SmartXs Pro with a 8 inch screen)

**Comment by plateaukao** [comment]
For first link, it does not work in my iReader Ocean2, but works on my phone.
For second link, it works on my iReader Ocean2 and my phone.

For first link, It looks like it shows different layout for tablet and phone size, and that's causing issues which makes EinkBro can't get the correct page height, nor change its page position. I have no way to fix this.

**Comment by xqdd** [comment]
I tried to fix it by find the `overflow-y:auto` element and scroll on it, work very well for first link. It's a bit of a tricky and not fully tested for other websites.

https://greasyfork.org/zh-CN/scripts/494503-high-contrast-theme-for-e-ink-displays-and-page-down
![image](https://github.com/plateaukao/einkbro/assets/20871761/a08886fe-1bb0-4ec6-bcc1-4df86efa16b0)


How about offer an option, force mapping the volume plus/minus
 key to Physical PageDown/PageUp/Space key?

**Comment by xqdd** [comment]
>  It looks like it shows different layout for tablet and phone size

Or can EinkBro offer a option to limit max screen width? Then the website wiil regard device as phone rather than tablet.

**Comment by plateaukao** [comment]
thanks for providing the script. I'll see what I can improve in EinkBro.
Also, providing option to map volume key to pageup pagedown is good suggestion, I'll add it to settings.

As for limiting device max width, I'll check whether it's good to provide or not.

**Comment by malnoxon** [comment]
The touch area on my boox tab ultra has the same issue with paging on https://feedly.com/i/my as well as the first link. Second link pages as expected.

**Comment by plateaukao** [comment]
@malnoxon 
it looks like feedly is using other techniques to scroll pages. So the fix does not work.

**Comment by Spiralo-Idioide** [comment]
I wondered if it was normal that when using fix scrolling, the scrolling is not instant, but rather linear, causing flashing on e-ink.
