### ISSUE TITLE
Can't copy Chinese words both in Android 13 and Android 14.

### ISSUE THREAD

**Issue by MaYuandong** [plateaukao/einkbro#372]
Chinese words become something like: "%AB%CD%33%A4".

**Comment by plateaukao** [comment]
please explain in more detail  how you use it.

**Comment by MaYuandong** [comment]
After I copy the Chinese words in EinkBro then share with EinkBro
 or press the EinkBro bottom after long press Chinese words in EinkBro,
(both do the same thing, search in google)
the Chinese words become  "%AB%CD%33%A4" in google search input area.

But it works correctly if I open a new tab and paste manually.

**Comment by plateaukao** [comment]
@MaYuandong 

I tried to fix it in https://github.com/plateaukao/einkbro/commit/74d0221f8f76a1bae47bb0ab847dbb8fc6c14d61.
But, not sure will it cause other issues.
You can wait for next release to check if it's fixed or causing other issue.
