### ISSUE TITLE
FR: Pop up dictionary

### ISSUE THREAD

**Issue by unacceptablet** [plateaukao/einkbro#379]
1. Koreader has a wonderful pop updictionary where, we can use multiple dictionaries, can format the text using .lua files & even search for a word from a dictionary entry. It can also customize font size in the pop up dictionary. Is anything like that possible in einkbro?

https://github.com/user-attachments/assets/7c5794e5-00c8-4a34-b00b-889d6916703f

2. Another option could be to integrate something like golden dict. (But I dont think it allows text formatting using .lua files like Koreaders' dictionary).
https://github.com/goldendict/goldendict

**Comment by plateaukao** [comment]
you could install eudict app, and then choose it from EinkBro after text selection. It can fulfill most of the features you want.

**Comment by unacceptablet** [comment]
> you could install eudic app, and then choose it from EinkBro after text selection. It can fulfill most of the features you want.

Will it take me away from Einkbro? I just want pop up so that I can stay on Einkbro. Is there a minimize button? Otherwise going back to Einkbro will be a hassle.

**Comment by plateaukao** [comment]
try it. :)
It shows a pop up as you wish. You can even modify the popup size (better than koreader does).

![EinkBro July 13 Screenshot](https://github.com/user-attachments/assets/ac4b244c-99e5-414f-9fec-e4d2088db5be)

![Eudic July 13 Screenshot](https://github.com/user-attachments/assets/3655243a-39c0-4ada-a902-b202ac3dc4fa)

**Comment by unacceptablet** [comment]
Sounds promising. Is there an English version of this app? The language is chinese / korean in both the PC version & the android version.

**Comment by plateaukao** [comment]
@unacceptablet 
 yes. it has English interface. 
and I believe it supports stardict format. You can get more info on its official site. 
Try using translate tools to read the descriptions on its official website.

**Comment by unacceptablet** [comment]
> @unacceptablet yes. it has English interface. and I believe it supports stardict format. You can get more info on its official site. Try using translate tools to read the descriptions on its official website.

Neither the windows app nor the android one has inteface language in English. (I used tranlate app to navigate, could not find the option to change the interface language. I downloaded from here:
https://www.eudic.net/v4/en/app/ting

**Comment by plateaukao** [comment]
It's already out of EinkBro's reach. 
Still, here's screenshots illustrating how you can navigate to Eudic's language settings. 
By default, the interface is  in Chinese, please translate strings on its interface to find the right item to click.
(if you still can't find it, please find other apps that support popup translations)

![S__7225354_0](https://github.com/user-attachments/assets/c0f03ab9-aa2a-46d6-a315-054e12f1b0b0)
![S__7225356_0](https://github.com/user-attachments/assets/e3eb2dcc-f3a4-4739-b283-f685d5eab0d3)
![S__7225357_0](https://github.com/user-attachments/assets/1b039d5e-0d4b-4813-a3cc-7be7fdfd861d)

![S__7225358_0](https://github.com/user-attachments/assets/5a211650-7db2-442a-b899-81fa18a714e0)

**Comment by unacceptablet** [comment]
> It's already out of EinkBro's reach. Still, here's screenshots illustrating how you can navigate to Eudic's language settings. By default, the interface is in Chinese, please translate strings on its interface to find the right item to click. (if you still can't find it, please find other apps that support popup translations)

Nice! This works better than all other android apps out there. Very fast & even has an Eink option in theme. Though it takes 2 taps instead of 1, it is still very good. But I have encountered a problem:

1. When the pop-up appears, Einkbro closes from behind. This happenes quite frequently. But I am not sure if this is a problem at Einkbros end or the OS on Boox Leaf 2 is killing apps that is in the back to save RAM. (But Koreader does not have the same problem).
2. Do you know any way to change the font size of the texts inside the pop-up? Could not find anything in the settings menu. 
3. Have you faced any difficulty with it detecting offline stardict dictionaries on you phone? It is detecting them fine on my boox leaf 2 (android 11) but it cant seem to be able to detect offline dictionaries in my Samsung phone (android 14) even after I gave it all permissions. 

Thanks again for finding this lightweight pop-up dictionary.

**Comment by plateaukao** [comment]
@unacceptablet 
Good to know it works for you. Please consult with Eudic app instead. I am not customer service for them.

**Comment by unacceptablet** [comment]
> 1. When the pop-up appears, Einkbro closes from behind. This happenes quite frequently. But I am not sure if this is a problem at Einkbros end or the OS on Boox Leaf 2 is killing apps that is in the back to save RAM. (But Koreader does not have the same problem).

I am beginning to suspect this is due to low RAM on the Leaf 2. I will try to collect the log file of the crash if I can (But Koreader doesnt crash). The problem is somewhat lessened when I disable all unncessary options on Eudic app & when I dont load too may news sites. 

> 2. Do you know any way to change the font size of the texts inside the pop-up? Could not find anything in the settings menu.

My bad. The option is present in settings > Font size. But Eudic app doen't respect the .lua configuration file and the dictionary entries looks garbage compared to Koreader pop-up dictionary.  
https://github.com/ankidroid/Anki-Android/issues/14141

> 3. Have you faced any difficulty with it detecting offline stardict dictionaries on you phone? It is detecting them fine on my boox leaf 2 (android 11) but it cant seem to be able to detect offline dictionaries in my Samsung phone (android 14) even after I gave it all permissions.

Settings > dictionary path works in leaf 2 but doesn't work on Samsung phone for some reason. But when I transfer the stardict dictionary folders using the built in "Wifi File Transfer" it works.

**Comment by unacceptablet** [comment]
I tested a few pop up dictionary apps on onyx boox leaf 2:

Eudic: only one in this list to support stardict. Has eink option in settings. Does not have navigation buttons for hopping between dictionary entries (useful if you are using multiple dictionaries), you have to swipe to scroll which is not always ideal on eink screen. 

Bludict: has navigation buttons for hopping between dictionary entries as well as page up & down. But leaves shadows after closing the pop up (you could try to somewhat fix it using Onyx's eink center). Creates a grey overlay everywhere other than the pop up area. 

DictTango: Seems comparatively slower on my eink device. But still a powerful app. Has navigatio button. When pressing down after the last dicitonary it shows a pop up saying "last dictionary reached" which is annoying to see on eink screen. Also creates a grey overlay everywhere other than the pop up area. 

Mdict: A bit faster than DictTango. Good overall. I might stick with it (if doesnt make eInkbro crash like eudic on my weak device).
