### ISSUE TITLE
CheckMediaAccessPermission: Not supported.

### ISSUE THREAD

**Issue by Layneboy** [plateaukao/einkbro#381]
I  [INFO:CONSOLE(1)] "Error", source: https://dropbox-api.arkoselabs.com/v2/2.8.1/enforcement.f4e33fa62e17087194e4d15bf1cc505b.js (1)
E  [ERROR:web_contents_delegate.cc(218)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
E  [ERROR:web_contents_delegate.cc(218)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
W  Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording

**Comment by plateaukao** [comment]
please follow issue template to report issue for easier investigation.
