### ISSUE TITLE
Spontaneous opening of home page when switching via Naviball on Boox

### ISSUE THREAD

**Issue by joshjob42** [plateaukao/einkbro#384]
**What device and app version are you using**
 - Device: Boox Go 10.3
 - OS: Android 12, Boox customized version 2024-06-21-12_3.5.3_899fd4030
 - EinkBro Version: 11.11.0 (07012102)

**Describe the bug**
When switching back to EInkBro via the Boox system Naviball, it seems to automatically open the homepage rather than returning to the tab you were in when you switched apps. Doesn’t happen with any other browser I’ve tested (Chrome, Firefox).

**To Reproduce**
1. Set Naviball to open EIB as one of the shortcuts.
2. Navigate to a website in EIB.
3. Open Naviball set to open EIB as one of the shortcuts, and select it. 

A new tab is generated with your home page. (Can also navigate to any other app and switch back via Naviball shortcut, and a new tab is generated.) Can be repeated to generate arbitrarily many such tabs.

**Expected behavior**
One should simply observe the app as if one switched back by opening from the home screen or app switcher, returning to whatever tab you were in before navigating away from the app.

**Screenshots**
Not really applicable; wouldn’t add information.

**Additional context**
I realize it may be an issue with Naviball but since it doesn’t happen with any other browser it suggests it’s an odd behavior with EIB specifically.

**Comment by plateaukao** [comment]
@joshjob42 
please check the snapshot version later, or wait for next version to be released.

**Comment by gety9** [comment]
@plateaukao 

I am experiencing somewhat similar issue on latest version (), steps:

1, open einkbro and open 3-5 tabs
2, switch to another app
3, press einkbro via naviaball's pinned apps shortcut (screenshot 1)
4, it switched to einkbro, but all tabs dissapear (screenshot 2)

(screenshot 1)
![Screenshot_2024-10-17_20-32-28](https://github.com/user-attachments/assets/0c64fead-2a39-4e3b-a38d-c9d5090866cb)

(screenshot 2)
![Screenshot_20241017-202617](https://github.com/user-attachments/assets/9bccc511-e399-4fa1-a1ef-941cea1cf5d4)

Should i open new issue, or is it better if you reopen this one?

**Comment by plateaukao** [comment]
@gety9 
I found another scenario that this might happen.
Try new builds with 52a4eac6091040b70a241dc3e83e6e349d1c8160
Or wait for next release.

**Comment by gety9** [comment]
@plateaukao latest update fixed it! Thank for your amazing work on the project.
