### ISSUE TITLE
Volume down of webpage not pre cached lazy load

### ISSUE THREAD

**Issue by axu2** [plateaukao/einkbro#390]
**What device and app version are you using**
 - Device: Hisense a9 8 gb
 - OS: android 11
 - EinkBro Version 11.7.0

**Describe the bug**
When I press volume down, part of the page loads instantly, and the rest at the bottom loads shortly after. In the worst case, half the screen loads in later. 

**To Reproduce**
Using an eink device. Maybe the CPU isn't the fastest. 

**Expected behavior**
When I click volume down, the whole page at the bottom should be pre cached and load instantly. 

**Screenshots**

https://github.com/user-attachments/assets/260e74d9-970b-4d29-b0cb-1cc2f6a937e1

**Additional context**

**Comment by plateaukao** [comment]
What refresh mode are you using on A9?
I tried the same behavior on my hisense A5 with Speed, or Smooth refresh mode, and it works well without any flickering; and the same behavior works well on my BOOX device with BSR chips.  I doubt it's how Hisense device refresh the screen. Maybe you could try Speed or Smooth refresh mode, or use device like BOOX Palma that has quick refresh chip in it.

**Comment by axu2** [comment]
It happens in balanced and clear mode. Unfortunately the a9 screen refreshes very fast so it can see the bottom of the page loading in slower.

**Comment by plateaukao** [comment]
@axu2 
In EinkBro, for scrolling behavior, I just call system webview to scroll down a specific offset and le the system webview handle the rest. There's no way to do any cache or preloading or pre-rendering. The issue for mihon does not help in this case. 

If you know how to do so, please send a PR. I'll be happy to review it.

**Comment by axu2** [comment]
I could take a look, though I have no android dev experience. Could you link the code section you think might be relevant?

**Comment by plateaukao** [comment]
@axu2 
Here's the codes that handles the page down/up logic. https://github.com/plateaukao/einkbro/blob/main/app/src/main/java/info/plateaukao/einkbro/view/NinjaWebView.kt#L512-L536

I doubt the laggish may be due to webview version or Hisense system implementation too. On BOOX devices, when I page down, it always refreshes whole screen instead.

**Comment by axu2** [comment]
Just for reference, here's a screen recording on my a9, if you step through it frame by frame you can see the bottom half loading in later. It flickers if I play back the video on my a9.

![image](https://github.com/user-attachments/assets/29e8c01b-7ef9-435c-ab96-7254223aed5a)


https://github.com/user-attachments/assets/43e1b067-a4ff-4390-8f1d-aa310e780225

**Comment by plateaukao** [comment]
not doable from my point of view. 
If you find it possible, please send a PR for this fix.
