### ISSUE TITLE
Turn off tap and hold behavior

### ISSUE THREAD

**Issue by ajdubovoy** [plateaukao/einkbro#398]
Hi, I’m really enjoying einkbro! I had a quick feature suggestion that should be easy to build. I noticed that when you tap and hold in either direction with touch mode enabled, it scrolls all the way to the bottom or top. The sensitivity on this is quite low, and I find it really easy to accidentally trigger. Would it be possible to add a setting just to turn this off when not needed?

**Comment by plateaukao** [comment]
@ajdubovoy 
will add an option in Settings > Behavior in near future.

**Comment by plateaukao** [comment]
added in https://github.com/plateaukao/einkbro/commit/c711b1e12c05b19ad438751ee9d9909cca3de32c
Please have a try or wait for next release.

**Comment by ajdubovoy** [comment]
Amazing, thank you so much!!
