### ISSUE TITLE
clicking on address bar shows the URL from the start instead of the end

### ISSUE THREAD

**Issue by alisonatwork** [plateaukao/einkbro#402]
**What device and app version are you using**
 - Device: Boox Palma
 - OS: Android 11
 - EinkBro Version: 11.14.0

**Describe the bug**
When you click on the address bar of the currently-loaded page, the keyboard pops up and focus goes to a text box with the current URL selected. This allows you to start typing a new URL and it will replace the existing URL. However the focus of the text is aligned to the start of the URL (`https://subdomain.example.com/s...`) instead of the end of the URL (`...ome/long/path-name?page=2`).

If the reason to click on the address is to change a parameter, this now requires scrolling sideways to get to the section you want to change, which is slow and painful to do on a touch screen device that does not have dedicated home/end/arrow keys.

Since changing a parameter at the end of the URL seems like a much more common case than changing the subdomain (changing the hostname altogether is no problem since you can just start typing to replace the whole selected text), and other mobile browsers tend to work this way, it seems to me that this is a bug and not a feature request.

This is related to my suggestion https://github.com/plateaukao/einkbro/discussions/401 that the URL should be shown in autocomplete results. Right now you don't know always what page you just loaded because the title in the autocomplete results does not make it obvious, so it would useful to just click on the address bar and immediately see and/or adjust the page number.

**To Reproduce**

1. Visit any site with a long URL, for example https://github.com/plateaukao/einkbro/discussions?page=2
2. Click on the address bar
-> URL is selected, but only the first part is shown

**Expected behavior**
URL is selected, and the last part should be shown

**Comment by plateaukao** [comment]
@alisonatwork 
Thank you for providing this suggestion and detail description.
I don't think most people use address bar to change parameters in url.
The example you raised is not reasonable. When url is with parameters like page=2, page=3, there should be a button or link more accessible on the web content to go to next pages. There's no need that user has to change url in address bar.

However, about your suggestion #401, I'll check other browser UI and see if it's better to add url into autocompletion results.

**Comment by alisonatwork** [comment]
Thank you for the response. I understand and agree with your point of view that website owners should make better websites. However, to add a bit more context for posterity: personally I manually change request parameters in the address bar multiple times per day, primarily to work around websites that have unfriendly paging behavior, but also to do things like remove tracking parameters from URLs I am copying from email or other websites to paste into a private tab etc.

It's certainly a power user feature to be able to edit the URL in the address bar before loading it, but I don't think it's so unusual that mobile browsers should deliberately make it difficult to do. On eink screens I think it's even more important to make sure that the cursor automatically appears in the most useful position by default, because it's generally more awkward to swipe around or move the cursor on eink devices than it is on standard touchscreen devices.

**Comment by plateaukao** [comment]
@alisonatwork 
By the way, currently EinkBro support pruning tracking parameters in url when sharing the link to other apps. However, to do it when a url is loaded, I can consider it too, so that there won't be manual removals most of the time.
