### ISSUE TITLE
Adaway rooted causing Error

### ISSUE THREAD

**Issue by bookteo** [plateaukao/einkbro#403]
Hi

I am using rooted adaway and it's throwing this error in the screen whenever I visit a website with ads on it. Can I disable the error message somehow? Or can you fix it showing up.? 

Thanks
![Screenshot_20240909-205918_EinkBro](https://github.com/user-attachments/assets/f88e735a-7d79-49f8-897a-636bc6d342d1)

**Comment by plateaukao** [comment]
go to Settings > Behavior
and uncheck "Show SSL error dialog"

**Comment by bookteo** [comment]
Thanks that works!!
