### ISSUE TITLE
Certificate Hostname mismatch

### ISSUE THREAD

**Issue by artemgur** [plateaukao/einkbro#404]
**What device and app version are you using**
 - Device: Onyx Boox Raphael, Google Pixel 6a
 - OS: Android 11, Android 14
 - EinkBro Version: v11.15.0 (latest version from F-Droid at 2024-16-09)

**Describe the bug**
On some websites Certificate Hostname mismatch error appears. The error window can be closed and the page can be browsed normally after that, but it's a bit annoying.
For example, the error consistently appears on this URL: https://m.vk.com/@3608477-moi-texty (a page of VK social network). The same page loads normally in other browsers on the same device.
I tested on two devices: Onyx Boox Raphael (ebook reader) and Google Pixel 6a (smartphone), the error appears on both.

**To Reproduce**
1. Open the following URL: https://m.vk.com/@3608477-moi-texty
2. Soon, "An Error Occured!!!" window will appear, with "Reason: Certificate Hostname mismatch" (like on the screenshot)

**Expected behavior**
The error shouldn't appear (as the same page loads normally in other browsers on the same devices).

**Screenshots**
Screenshot from Google Pixel 6a:
![image](https://github.com/user-attachments/assets/3f068e2b-5d7e-4dc3-ae44-6ddef3d9fe4a)

**Comment by plateaukao** [comment]
@artemgur 
Go to Settings > Behavior, and uncheck "Show SSL error dialog"

**Comment by artemgur** [comment]
Thank you

**Comment by Farzat07** [comment]
The same problem is happening to me with Coursera.

Why does this happen though? False positives like these disrupt the detection of real cases of the error.

**Comment by plateaukao** [comment]
You could ask Coursera, the website, or Google who provides WebView component, why this happens.
