### ISSUE TITLE
Chinese language is default on devices with Russian locale (at least)

### ISSUE THREAD

**Issue by artemgur** [plateaukao/einkbro#405]
**What device and app version are you using**
- Device: Onyx Boox Raphael, Google Pixel 6a
- OS: Android 11, Android 14
- EinkBro Version: v11.15.0 (latest version from F-Droid at 2024-16-09)

**Describe the bug**
On devices with Russian locale (didn't test with other locales), Chinese language is default in the browser. It can be very confusing for new users, because with Chinese localization it's unclear how to reach the language settings (I, personally, had to google it).
I tested on two devices: Onyx Boox Raphael (ebook reader) and Google Pixel 6a (smartphone), the issue appears on both.

**To Reproduce**
1. Install the browser on a device with Russian locale
2. Open the browser, Chinese language will be default

**Expected behavior**
Ideally, browser default language should match system locale.
Alternatively, language selection window should be shown to the user on the first launch of the app.
Or, at least, English language should be default instead, as lingua franca.

**Comment by rhein** [comment]
Can confirm this on Android 11 (LineageOS) with English locale as well.

**Comment by plateaukao** [comment]
@rhein 
it's fixed in 11.16.0.

**Comment by rhein** [comment]
Thanks @plateaukao - can confirm it is working in 11.16.0 for me.
