### ISSUE TITLE
Toolbar not scrollable

### ISSUE THREAD

**Issue by wasu-code** [plateaukao/einkbro#412]
**What device and app version are you using**
 - Device: Redmi 9
 - OS: Android 11
 - EinkBro Version: v11.17.0 (09211243)

**Describe the bug**
Toolbar (and popup invoked from it) is not scrollable. If user have more icons than screen can fit it's not possible (anymore) to scroll and see them all.

**To Reproduce**

Toolbar:  
1. Add many toolbar icons (more than screen can fit)
2. Try to scroll to first/last icon
3. Rotate screen to make sure that icons are actually there

Popup:  
1. Use EinBro when in horizontal mode
2. From toolbar click on hamburger manu to open popup
3. Notice you can't scroll to bottom icons

**Expected behavior**
You can scroll toolbar horizontally and popup vertically as it was possible before.

**Screenshots**
![Screenshot_20240926085937](https://github.com/user-attachments/assets/5a74416d-454b-4f75-b4a5-c4cb3b931247)  
*Only some icons visible, scrolling not possible*

![Screenshot_20240926085956](https://github.com/user-attachments/assets/464327ef-f567-4d95-82f6-7cebf6d95db4)  
*All icons visible in horizontal mode, no need for scrolling*

![Screenshot_20240926090002](https://github.com/user-attachments/assets/3499a9e6-4173-4427-b1e7-c1cb2a58acc4)  
*Popup in horizontal mode not scrollable vertically*

![Screenshot_20240926090008](https://github.com/user-attachments/assets/82a83cd3-a37d-4128-9b7d-627d58bc5778)  
*In vertical mode all icons in popoup fit the screen, no need for scrolling*

**Comment by plateaukao** [comment]
should have been fixed in https://github.com/plateaukao/einkbro/commit/c5a1a101d1d453860da7f4d7ba6f5f35554cb31d
