### ISSUE TITLE
Bookmarks are exported as . txt files but not . json

### ISSUE THREAD

**Issue by Myron472** [plateaukao/einkbro#418]
When exporting bookmarks in EinkBro it exports them into *bookmark.txt* file, but this file is actually a JSON file. The problem is that EinkBro doesn't let me pick txt files for some reason...
So default bookmark file name should be ***bookmarks.json*** instead.

**Comment by plateaukao** [comment]
Hi, @Myron472 
Could you specify on what devices that it does not work to select the bookmark file? On all my devices, it works.

**Comment by Myron472** [comment]
Sorry, this issue happened because bookmarks file wasn't properly synced in my cloud storage. Bookmarks file is importing fine now 👌
