### ISSUE TITLE
Einkbro stops after a short view of the page 

### ISSUE THREAD

**Issue by MasterPlexus** [plateaukao/einkbro#429]
- Device: pixel 7pro
 - OS: Android 14
 - EinkBro Version: not able to See, AS it clises to fast, but its the last version

It makes no difference to open einkbro manually, or to.follow a link from a other APP. Since some days the APP opens for some seconds, show the last opend page, or the page comming from a link, and closes then without ans message.

**Comment by plateaukao** [comment]
@MasterPlexus 
How to check app version: Go to Settings, it's listed in last item.

Please provide a more clear reproducing steps. For example, 
in what specific app, open what kind of the link (specific url), and what happens.
If it's hard to describe, please provide a video link that shows the issue.
it'll be easier for me to check what went wrong.

**Comment by plateaukao** [comment]
Please try latest version again.
