### ISSUE TITLE
Sometimes when switching apps EinkBro shows blank page.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#433]
**What device and app version are you using**

 - Device: Boox NoteAir2
 - OS: Android 11
 - EinkBro Version [e.g. latest (12.2.0)]

**To Reproduce**
Steps to reproduce the behavior.
1. Go to any website (wait for page to be fully loaded)
2. Switch to another app (i use Boox nav ball for this)
3. Switch back to EinkBro (i use alt+tab on physical keyboard)
= blank page (screenshot attached)

(screnshot)
![Screenshot_20241018-195415](https://github.com/user-attachments/assets/37b0bfe6-0726-48d9-bd07-704dfe865bca)

details:
-, i don't think it's Android killing EinkBro cause i set "do not freeze" and "stay active in the background"

**Comment by plateaukao** [comment]
I'll check the behavior when I found time connecting my device to physical keyboard.

**Comment by plateaukao** [comment]
I can't reproduce it so far with latest version.

**Comment by Mrazator** [comment]
I can repro consistently when visiting https://excalidraw.com/, it loads for a few milliseconds but disappears right after. Wasn't an issue few weeks back, but might have had some quite old version back and also did a big Boox firmware update.

https://github.com/user-attachments/assets/4f916c6a-2666-4b0e-b851-2fb694764f94

EinkBro v10.13.1

Can I access somehow access logs / console to give you more info?

**Comment by Mrazator** [comment]
Thanks! The latest version does indeed fix this.
