### ISSUE TITLE
Avoid beta during update check

### ISSUE THREAD

**Issue by winstonma** [plateaukao/einkbro#441]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**

 - EinkBro Version: v12.4.0

**Describe the bug**

einkbro got updated to [v14.0.0-beta](https://github.com/plateaukao/einkbro/releases/tag/v14.0.0-beta) while checking for update.

**To Reproduce**
Steps to reproduce the behavior.

Example description:
1. Go to 'Settings'
2. Click on 'About EinkBro v12.4.0'
3. Scroll down to 'Update to Latest Release'
4. Update to v14.0.0 beta
  
**Expected behavior**

einkbro only update from the non-beta channel

**Comment by plateaukao** [comment]
thanks for reporting it.
will check how to disable it.
