### ISSUE TITLE
Bookmarks font size far too small on entering URL

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/einkbro#447]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**

 - Device: Onyx BOOX Max Lumi
 - OS: Android 10
 - EinkBro Version: 14.0.0

**Describe the bug**

The font used to display matching bookmarks when editing URLs (if enabled) is far too small.

**To Reproduce**

Steps to reproduce the behavior.

Example description:
1. Ensure that "Show Bookmarks when editing URL" is enabled in settings (Behaviour tab).
2. Tap on URL widget on toolbar.
3. Matching bookmarks will be displayed in two columns in the webpage area.  Font is infinitesimally small.  Us olds can't read that stuff. 

Note too that under Onyx's app configuration I have DPI set to 250 for EinkBro.  If I scale that up, app controls are too large.

Related issue is that the font size for URL entry is _also_ smallish, but not nearly so bad as the bookmarks.

** What's the behavior on following similar browsers **

n/a

**Do not report that it works in CHROME, FIREFOX, or EDGE, BRAVE. That does not help. Since these are full-fledge browsers**
  
**Expected behavior**

Font size should be roughly the default system font size for Android.  *Maybe* a point or two smaller, but no less.

Change seems to have occurred sometime between v 11.mumble, which I'd had pinned for a while.  I noticed the small fonts after unpinning and upgrading EinkBro recently.

**Screenshots**

**Additional context**

Again:  my DPI settings may be affecting this, and font size for URL entry is also painfully small, though not quite as bad as bookmarks.

I'd prefer EinkBro simply follow Android system font sizes for this and other App text (e.g., settings, toolbar descriptions, etc.), rather than, say, adding Yet Another Configuration for app font size.

If a screenshot would help I can try generating some.  I may be able to install an older version of the app and contrast the older and current (14.0.0) appearance.

**Comment by plateaukao** [comment]
I enlarged the font and verified it on BOOX Max3. Should be better now.

**Comment by dredmorbius** [comment]
Thanks!  Target release?

**Comment by plateaukao** [comment]
already merged codes. should be next version.
