### ISSUE TITLE
pageUp / pageDown buttons stop working.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#60]
Einkbro v8.21.0
Boox Note Air 2, Version 3.2_0ae74d7d5d (latest)

pageUp / pageDown buttons stop working upon:
1, reaching end of the page
2, opening link

Steps to replicate case 1
Open page,
Enable buttons, 
pageDown to very end
try pageUp = it does not work

Steps to replicate case 2
Search for smng in google
Enable buttons (they work now)
long press on any result
select "New tab (background)"
try pageUp or pageDown = they do no work

Turning on / off buttons solves the issue, but it's annoying

**Comment by plateaukao** [comment]
thanks for reporting the issues. About case 1, I will look into it. When it happens, if you click page up more times, does it work?

As for case 2, it's beeen found and fixed. Should be working in next version.

**Comment by gety9** [comment]
@plateaukao 
Case 2: great to hear that it will be fixed with next release.
Case 1: nope, clicking page up more times doesn't help, even disabling/enabling (finger pressing circle icon) doesn't help; only manual scroll up fixes it.

**Comment by gety9** [comment]
@plateaukao 
Case 1: update. Once I added page up / page down icons to toolbar (before I had only press circle icon) now I can go back by pressing several times.
However I need to press page up button as many times (to make it responsive again) as press down was pressed after reaching end of the page.

**Comment by plateaukao** [comment]
it looks like it's overscrolled, so you need to press up button several times to make it back. I'll check what I can improve.

**Comment by gety9** [comment]
Yes, it was overscrolled - basically if i overscoll x times, i need to unscroll x+1 times, it's minor issue - closing cause not important and not that useful.

**Comment by plateaukao** [comment]
@gety9 
Overscrolled issue should have been fixed in version v9.21.0. Please have a try. :)

**Comment by gety9** [comment]
@plateaukao 

works! thank you for amazing work on the project.
