### ISSUE TITLE
Add ability to rebind shortcuts.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#73]
I think it's good idea to have possibility to rebind shorts because:

- different users have different muscle memory depending on OS/software environment they are used to.
For example Windows guy might want to have "search in page" as "ctrl+f" instead of "/"; or "new tab" as "ctrl+t" instead of "t", etc.

- current short cuts don't have leader key, it's good practice for environments where you can activate mode and then diactivate mode (Vim, etc), or where there is only 1 mode (consuming pages (reading/movies) but no interacting with them), but it does not work well on pages where you can type (say comment or search) cause state depends only on if input field is selected which is unreliable (accidental out of input area tap, reaching end of form, tab key, etc can change the state and typing "o" for "ok" will "focus on bar")

**Comment by plateaukao** [comment]
@gety9 

Now there's an option to turn off VI key bindings. :)
https://github.com/plateaukao/browser/releases/tag/v8.31.0

As for more key binding options, I will consider it in future releases.

**Comment by plateaukao** [comment]
For issue part, it's fixed. 
As for adding configurable key bindings, since it's only a small browser, I won't add this feature any time soon. So, close for now.
