### ISSUE TITLE
Can't download image on android 9

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#91]
https://i.ylilauta.org/96/45/96453830cad9b5a7.jpg

**Comment by Kita2345** [comment]
Hi,
This problem is caused by not supporting TLS1.3 certificate. But since TLS1.3 is provided from Android 10 or higher, it seems that the problem will still occur in Android 9 and lower versions.
It appears normally on the web, but the download is done on Android.

**Comment by plateaukao** [comment]
Android's Download manager does not support downloading it, so I won't fix it.
