### ISSUE TITLE
Download dialog does not decode multibyte file name 

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#93]
Steps to reproduce
Download the test file here: https://s41.lanzoug.com/022810bb/2021/10/21/56f7d97e19ac3437dbb0fbddbc113241.txt?st=4MwiZdypwtTIYLwx55O2Iw&e=1646018350&b=VOJa4gKvVbZXlAXUUOZUxgbUCrJR6wa2Cb8IlVTeVLAJ7lrRBOxY8lGRBHxRdVQoVnc_c&fi=54792024&pid=114-122-4-151&up=2&mp=1&co=1

Expected behaviour
Decoded as: 中文文件名测试.txt

Actual behaviour
File name could not be decoded:
%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E5%90%8D%E6%B5%8B%E8%AF%95.txt

**Comment by plateaukao** [comment]
Thanks for reporting this issue, I'll fix it in future versions. Before this happens, you can just rename the download file name manually.

**Comment by plateaukao** [comment]
rename feature is provided. please rename the file when default name is not appropriate.
