### ISSUE TITLE
Slow / choppy scrolling 

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#94]

**Comment by plateaukao** [comment]
what app version, what website, what device, does it happen in previous version?

**Comment by Kita2345** [comment]
After recent update, slow performance. Scrolling through - any - website is choppy
ZenFone Max Pro (M2)
Android 9

**Comment by dredmorbius** [comment]
@Kita2345 Is that an e-ink device or emissive?

For e-ink, scrolling experience tends to be poor at higher quality levels.  That's my experience on an Onyx BOOX Max Lumi.

With that device, either paginated navigation (supplied by Einkbro) or setting refresh to "Speed", "A2", or "X mode" improves scroll.

When using the "Normal" system scroll, it's possible to set refresh to a lower quality when scrolling.  If high-quality display is set directly via "Regal", then scrolling is ... a disaster.  In _any_ app.

My understanding is that display modes are defined by EInk Corp. itself in the display device(s).  I'm not sure what your device specifically offers, but you might want to look at the system-wide E-ink settings, or the app-specific management.  Onyx offers app-level E-ink configuration, your mileage may vary.

**Comment by plateaukao** [comment]
close for now. I tried on Huawei P20 PRO with Android 9 and it scrolls smoothly.
